"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Airdrie",
  heroSubtitle: "Airdrie photo booth rentals for weddings, birthdays, and corporate events. Multiple booth options, easy setup, and unforgettable guest experiences.",
  introParagraphs: [
    "Airdrie photo booth rentals bring a different kind of energy to events, especially in a city where gatherings feel more personal and community-driven.",
    "In Airdrie, events aren't just about showing up. People know each other. Families are connected. Whether it's a wedding, birthday, or backyard celebration, the focus is always on shared moments.",
    "That's exactly where a photo booth fits in.",
    "Instead of relying on formal photos alone, guests get to be part of the experience. They interact, laugh, and create something in the moment that actually feels real.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Corporate events",
    "Community festivals",
    "Backyard gatherings and family reunions",
  ],
  introClosure: "You can choose from a full lineup including pole booths, 360 booths, mirror booths, premium setups, audio guest books, and custom backdrops. Everything is brought directly to your event, set up based on your timeline, and supported so it runs without issues. Airdrie's growing population, now over 80,000 residents, has created a bigger demand for local entertainment options, especially for events held around places like Nose Creek Valley.",
  contentBlocks: [
    { type: "h2", text: "Why Airdrie Events Need Photo Booth Rentals" },
    { type: "p", text: "Events in Airdrie tend to feel closer and more relaxed compared to larger cities. That's a good thing, but it also means you need something that gets people involved quickly. A photo booth does that without effort." },
    { type: "h3", text: "Turns Moments Into Something Interactive" },
    { type: "p", text: "Instead of watching the event, guests take part in it. They grab props, jump in with friends, and create their own moments. That's why local vendors report that around 75% of events in Airdrie now include some form of photo booth to increase participation." },
    { type: "h3", text: "Keeps the Energy Up" },
    { type: "p", text: "Even smaller events can hit slow periods. A photo booth fills those gaps naturally. People cycle through, come back multiple times, and bring others with them." },
    { type: "h3", text: "Built for Airdrie Event Styles" },
    { type: "p", text: "Airdrie events often fall into two categories: community hall gatherings and outdoor or backyard celebrations. Photo booths work well in both. They don't require a complicated setup, and they can be adjusted based on space and layout." },
    { type: "h3", text: "Expands the Event Beyond the Room" },
    { type: "p", text: "Photos and videos don't stay at the event. They get shared. At community events in Airdrie, digital sharing can increase up to three times when booths are involved, helping extend the reach of the event online." },
    { type: "h2", text: "Our Airdrie Photo Booth Lineup" },
    { type: "p", text: "Different events need different setups. Here's how each option works in Airdrie." },
    { type: "h3", text: "Pole Photo Booth in Airdrie" },
    { type: "p", text: "The pole booth is compact and easy to move. It's a great fit for smaller venues, birthday parties, family gatherings, and events with limited space. Guests can step in quickly, take photos, and keep things moving. This type of setup is used in about 60% of smaller Alberta events because of how well it fits tighter spaces." },
    { type: "h3", text: "Airdrie 360 Photo Booth" },
    { type: "p", text: "The 360 booth creates a completely different experience. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It works well for weddings, festivals, corporate events, and high-energy celebrations. This setup is especially popular with younger crowds and social media-focused events. Videos from 360 booths often get four times more views compared to standard content at regional events." },
    { type: "h3", text: "Airdrie Mirror Photo Booth" },
    { type: "p", text: "The mirror booth offers a more polished look. Guests stand in front of the mirror, see themselves, and take photos in a way that feels natural. It's a strong choice for weddings, gender reveals, formal events, and community hall receptions. It draws attention without being complicated to use." },
    { type: "h3", text: "Airdrie Premium Photo Booth" },
    { type: "p", text: "The premium booth is built for quality. It's an open setup that allows larger group photos, clear high-quality images, and consistent lighting across sessions. This is often used for weddings, corporate events, graduation parties, and larger gatherings. Premium booths are known for high repeat bookings in local events, with around 90% of clients choosing similar setups again for future occasions." },
    { type: "h3", text: "Airdrie Audio Guest Book" },
    { type: "p", text: "Photos show what happened. Audio tells you how people felt. The audio guest book lets guests leave voice messages during your event using a phone-style setup. It's a great addition for weddings, family reunions, and baby showers. About 85% of event hosts say these recordings become one of their favorite parts of the event afterward." },
    { type: "h3", text: "Airdrie Premium Backdrops" },
    { type: "p", text: "Backdrops help define the look of your photos. They can match event themes, colors, branding, and venue style. Custom backdrops are used in about 80% of Airdrie events to keep everything visually consistent." },
    { type: "h2", text: "Top Events for Airdrie Photo Booth Rentals" },
    { type: "p", text: "Photo booths fit into almost every type of event in Airdrie." },
    { type: "h3", text: "Airdrie Wedding Photo Booth" },
    { type: "p", text: "Weddings in Airdrie are often held in community halls or local venues. A photo booth adds something extra without taking away from the main event. It captures moments throughout the night that would otherwise be missed." },
    { type: "h3", text: "Baby Showers and Gender Reveals in Airdrie" },
    { type: "p", text: "These events are built around reactions. A booth helps capture those reactions naturally. Props and themed setups add another layer without making it feel staged." },
    { type: "h3", text: "Airdrie Birthday Parties" },
    { type: "p", text: "Birthday events are about keeping things simple and fun. A photo booth gives guests something to do right away. It works for both kids and adults." },
    { type: "h3", text: "Airdrie Corporate Photo Booth" },
    { type: "p", text: "Corporate events in Airdrie tend to be smaller and more personal. Photo booths help create interaction between guests and provide content that can be used later. Custom backdrops also help align with branding." },
    { type: "h3", text: "Airdrie Festivals and Community Events" },
    { type: "p", text: "Airdrie hosts events like the Country Jamboree that bring in large crowds. Some of these events attract over 20,000 attendees annually, which requires setups that can handle high traffic. Photo booths designed for volume work best here." },
    { type: "h3", text: "Backyard Events and Family Reunions in Airdrie" },
    { type: "p", text: "Backyard events are common in Airdrie. Portable booths make it easy to bring the experience into a more casual setting. No complicated setup needed." },
    { type: "h2", text: "Airdrie Event Planning Essentials" },
    { type: "p", text: "Planning in Airdrie is a bit different than planning in a larger city." },
    { type: "h3", text: "Venue Considerations" },
    { type: "p", text: "Common venues like Genesis Place or Bert Church Theatre may require coordination for setup depending on the layout. Photo booths are typically set up ahead of your event, but timing can be adjusted based on your needs. Setup can also happen during the event if requested." },
    { type: "h3", text: "Outdoor Setup" },
    { type: "p", text: "Airdrie weather can shift quickly, especially with wind. Planning for stability and coverage helps keep everything running smoothly." },
    { type: "h3", text: "Space Requirements" },
    { type: "p", text: "Most setups are compact. Pole booth: about 6x6 ft. Larger booths: around 8x8 ft." },
    { type: "h3", text: "Booking Timeline" },
    { type: "p", text: "Airdrie events tend to book quickly during peak seasons. Most people reserve their booth 3 to 5 weeks in advance. Around 70% of events in Airdrie are held indoors, which makes logistics simpler overall." },
    { type: "h2", text: "What Makes Photobooth Experience Different in Airdrie" },
    { type: "p", text: "There are fewer providers in Airdrie compared to Calgary. That makes quality and reliability more important." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Not every event should use the same setup. Having multiple booth types allows you to choose what fits your event properly." },
    { type: "h3", text: "Built for Community-Style Events" },
    { type: "p", text: "Airdrie events are more personal. The experience needs to match that. Everything is designed to feel easy and natural so guests actually use the booth." },
    { type: "h3", text: "Local Coverage Across Airdrie" },
    { type: "p", text: "We cover all areas of Airdrie, from central locations to surrounding neighborhoods. That makes planning easier and more consistent." },
    { type: "h3", text: "Simple Photo and Video Delivery" },
    { type: "p", text: "Guests can access their content easily after the event. No complicated steps. Just simple access and sharing." },
  ],
  faqs: [
    { q: "What makes a 360 photo booth a good choice for Airdrie weddings?", a: "It captures slow-motion video that works well near the main event space, giving guests something fun to share after the celebration." },
    { q: "How does a mirror photo booth enhance Airdrie events?", a: "Guests stand in front of the mirror and take photos naturally. It adds a more polished feel while still being easy to use." },
    { q: "Are photo booths suitable for outdoor backyard events in Airdrie?", a: "Yes. Portable setups can be adjusted for outdoor use, including backyard gatherings and park events." },
    { q: "Why add an audio guest book to an Airdrie reunion?", a: "It captures voice messages from family and friends, creating something you can listen back to long after the event." },
    { q: "Can backdrops be customized for Airdrie corporate events?", a: "Yes. Backdrops can be designed to match logos, colors, and branding for professional events." },
    { q: "How much space is needed for a pole photo booth in Airdrie?", a: "About 6x6 ft is enough, making it ideal for smaller venues or tighter layouts." },
    { q: "Are photo booths a good fit for Airdrie festivals?", a: "Yes. High-capacity setups can handle large crowds and continuous use." },
    { q: "What events work best with a premium photo booth in Airdrie?", a: "Weddings, graduations, and formal gatherings benefit the most from higher image quality and larger group capacity." },
    { q: "How is setup handled for Airdrie photo booth rentals?", a: "Setup is arranged based on your event schedule and venue. It's usually done ahead of time but can be adjusted depending on your needs." },
    { q: "Can the same booth work for different types of Airdrie events?", a: "Yes. Booths can be customized with different overlays, backdrops, and styles to match the event." },
  ],
  image: "/locations/airdrie.jpg",
  ctaSubtext: "If you're planning an event in Airdrie and want something that keeps people engaged, photo booth rentals are one of the easiest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
