"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Banff",
  heroSubtitle: "Banff photo booth rentals for luxury weddings and mountain events. Premium booth options, weather-ready setups, and seamless service.",
  introParagraphs: [
    "Banff photo booth rentals are built for events where the setting already feels unforgettable.",
    "In Banff, you're not just hosting an event. You're bringing people into one of the most recognized mountain destinations in the world. From castle-style ballrooms to outdoor terraces overlooking peaks, every detail matters.",
    "That includes how your guests experience the event.",
    "A photo booth adds something interactive without taking away from the atmosphere. It gives guests a reason to step in, engage, and create moments that feel natural in a setting that already looks incredible.",
  ],
  eventTypes: [
    "Destination weddings",
    "Baby showers",
    "Birthday celebrations",
    "Gender reveals",
    "Mountain festivals",
    "Corporate retreats",
    "Après-ski parties and reunions",
  ],
  introClosure: "You can choose from pole booths, 360 booths, mirror booths, premium setups, audio guest books, and custom Rocky Mountain backdrops. Everything is delivered, set up based on your event, and managed with an understanding of Banff's unique logistics. Banff sits at around 4,500 feet elevation, and chinook winds can reach 50 km/h or more. Booth setups need to be stable, secure, and ready for changing conditions.",
  contentBlocks: [
    { type: "h2", text: "Elevate Banff Events with Mountain-Ready Booths" },
    { type: "p", text: "Events in Banff come with a different level of expectation. Guests travel in. Venues are elevated. The setting is already premium. The experience needs to match." },
    { type: "h3", text: "Built for High-End Venues" },
    { type: "p", text: "Banff venues aren't typical. You're dealing with historic ballrooms, mountain-facing terraces, luxury hotels, and high-capacity wedding spaces. A photo booth needs to fit into that environment without disrupting it." },
    { type: "h3", text: "Designed for Weather and Elevation" },
    { type: "p", text: "Banff weather shifts quickly. Winter can drop to -30°C, while chinook winds can bring sudden changes. Booth setups need to operate across a wide temperature range, from about -20°C to +25°C. Wind stability is just as important as the booth itself." },
    { type: "h3", text: "Creates Content That Matches the Setting" },
    { type: "p", text: "Photos and videos taken in Banff don't just capture people. They capture the environment. Mountain views, architecture, and natural light all add to the final result. That's what makes the content stand out and get shared." },
    { type: "h2", text: "Your Premium Banff Booth Collection" },
    { type: "p", text: "Each booth option is designed to fit different parts of a Banff event." },
    { type: "h3", text: "Compact Pole Photo Booth in Banff" },
    { type: "p", text: "The pole booth is compact and easy to place. It works well for smaller event spaces, lounge areas, corporate retreats, and indoor receptions. It fits into tighter layouts like the Rundle Salon at Fairmont Banff Springs, which accommodates smaller guest counts." },
    { type: "h3", text: "Banff 360 Photo Booth" },
    { type: "p", text: "The 360 booth brings movement and energy. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It's a strong choice for wedding receptions, festival events, corporate celebrations, and après-ski gatherings. It works especially well in spaces with strong visual backdrops, like terraces or ballrooms with mountain-facing windows." },
    { type: "h3", text: "Banff Mirror Photo Booth" },
    { type: "p", text: "The mirror booth adds a refined, elevated feel. Guests step in front of the mirror and take photos naturally. It's a good fit for bridal showers, indoor receptions, formal events, and luxury venues. It blends into the environment without feeling out of place." },
    { type: "h3", text: "Banff Premium Photo Booth" },
    { type: "p", text: "The premium booth is built for larger events. It allows group photos, consistent lighting, and clean high-quality images. It's often used for weddings with larger guest counts, corporate galas, and ballroom events. The open layout works well in spaces like the Castle Ballroom at Fairmont Banff Springs, which can accommodate up to 400 guests." },
    { type: "h3", text: "Banff Audio Guest Book" },
    { type: "p", text: "Photos capture the visuals. Audio captures the emotion. The audio guest book allows guests to leave voice messages during the event. It's often used for weddings, destination gatherings, and corporate retreats. Placed near seating areas or lounges, it becomes a quiet moment within a larger event." },
    { type: "h3", text: "Banff Premium Backdrops" },
    { type: "p", text: "Backdrops help frame the experience. In Banff, they're often designed to complement the surroundings. Options can include mountain silhouettes, evergreen forests, and custom venue-matching designs. They help maintain consistency across all photos while still fitting the environment." },
    { type: "h2", text: "Perfect Banff Events for Photo Booth Rentals" },
    { type: "p", text: "Photo booths work across all types of Banff events." },
    { type: "h3", text: "Banff Wedding Photo Booth" },
    { type: "p", text: "Banff is known for destination weddings. Venues like Fairmont Banff Springs, Rimrock Resort, and Banff Park Lodge all offer different layouts, but the goal is the same: create a memorable experience. A photo booth adds something interactive without taking away from the elegance of the event." },
    { type: "h3", text: "Corporate Retreats in Banff" },
    { type: "p", text: "Banff is a common destination for corporate retreats. Teams come for a mix of work and downtime. A photo booth gives them something to interact with outside of scheduled activities. Locations like the Juniper Hotel or Elk + Avenue are often used for these events." },
    { type: "h3", text: "Banff Festivals and Community Events" },
    { type: "p", text: "Events like the Banff Centre Mountain Festival and Banff Winter Festival bring in steady crowds across multiple days. These events require setups that can handle continuous use while adapting to changing conditions." },
    { type: "h3", text: "Lake Louise and Surrounding Events" },
    { type: "p", text: "Events at nearby locations like Lake Louise often fall within the same planning scope. Portable booth setups make it possible to extend service into surrounding areas without changing the experience." },
    { type: "h3", text: "Private Chalets and Mountain Homes" },
    { type: "p", text: "Neighborhoods like Tunnel Mountain host private events and smaller gatherings. Photo booths can be set up in these environments without requiring complex logistics." },
    { type: "h2", text: "Banff Venue-Specific Planning Guide" },
    { type: "p", text: "Planning in Banff requires attention to detail." },
    { type: "h3", text: "Fairmont Banff Springs" },
    { type: "p", text: "The Castle Ballroom offers 6,000 sq ft of space, capacity for up to 400 guests, and power access in multiple areas. Load-in requires coordination through the service entrance off Banff Avenue, often with valet scheduling. The Rundle Salon is a smaller space, ideal for compact booth setups." },
    { type: "h3", text: "Rimrock Resort" },
    { type: "p", text: "The Weddings Deck terrace faces Sulphur Mountain and is exposed to strong wind conditions. Anchoring is important in this environment. The Mount Rundle Ballroom allows indoor setups with access to outdoor views." },
    { type: "h3", text: "Banff Park Lodge" },
    { type: "p", text: "The Cascade Room offers space for up to 150 guests, direct patio access, and flexible placement options. Power access near patio doors makes indoor-outdoor setups easier." },
    { type: "h3", text: "Outdoor and Festival Placement" },
    { type: "p", text: "During larger events, positioning matters. Placing booths near entrances or high-traffic areas increases usage without disrupting flow." },
    { type: "h2", text: "Why Banff Wedding Planners Choose Photobooth Experience" },
    { type: "p", text: "Banff events are different. The service needs to match the setting." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events require different setups. Having multiple booth types allows you to choose what fits best." },
    { type: "h3", text: "Built for Mountain Conditions" },
    { type: "p", text: "Wind, elevation, and temperature all play a role. Setups are designed to handle those conditions." },
    { type: "h3", text: "Experience with Banff Venues" },
    { type: "p", text: "Working in Banff requires understanding venue logistics, access points, and setup requirements. That helps everything run smoother." },
    { type: "h3", text: "Simple Photo and Video Access" },
    { type: "p", text: "Guests can access their content after the event without extra steps." },
  ],
  faqs: [
    { q: "Is a 360 photo booth a good fit for Fairmont Banff Springs weddings?", a: "Yes. It captures movement and energy during receptions, especially in large spaces like the Castle Ballroom." },
    { q: "How does a mirror photo booth work at Banff events?", a: "Guests stand in front of the mirror and take photos naturally. It works well in both formal and casual environments." },
    { q: "Can photo booths handle wind at Banff outdoor venues?", a: "Yes. Setups are planned with stability in mind to handle chinook winds and outdoor conditions." },
    { q: "Why add an audio guest book to a Banff wedding?", a: "It captures voice messages from guests, creating something more personal than photos alone." },
    { q: "Can backdrops match Banff venues?", a: "Yes. Backdrops can be designed to complement the environment and overall event style." },
  ],
  image: "/locations/banff.jpg",
  ctaSubtext: "If you're planning an event in Banff and want something that keeps people engaged while matching the setting, photo booth rentals are one of the best ways to do it. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
