"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Canmore",
  heroSubtitle: "Canmore photo booth rentals for weddings, festivals, and retreats. Mountain-ready setups, multiple booth options, and seamless service.",
  introParagraphs: [
    "Canmore photo booth rentals bring something different to events set against one of the most unique backdrops in Alberta.",
    "In Canmore, the setting already does a lot of the work. Mountains, open air, and smaller, more intentional gatherings. But what turns those events into something memorable isn't just the location. It's what people do while they're there.",
    "That's where a photo booth fits in.",
    "It gives guests something to step into right away. No waiting around. No forced moments. Just quick, natural interactions that capture the energy of the event as it happens.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Festivals and community events",
    "Corporate retreats",
    "Backyard gatherings and reunions",
  ],
  introClosure: "You can choose from pole booths, 360 booths, mirror booths, premium setups, audio guest books, and custom alpine-inspired backdrops. Everything is delivered and set up based on your event, with support so it runs smoothly in both indoor and outdoor environments. Canmore sits at around 4,400 feet elevation, and wind conditions in the Bow Valley regularly reach 30 to 50 km/h. That makes setup and stability a key part of any event planning.",
  contentBlocks: [
    { type: "h2", text: "Power Up Your Canmore Event" },
    { type: "p", text: "Events in Canmore aren't typical. You're often dealing with outdoor venues, changing weather, elevated terrain, and scenic but unpredictable conditions. A photo booth needs to work within all of that." },
    { type: "h3", text: "Built for Mountain Conditions" },
    { type: "p", text: "Wind matters in Canmore. Especially in fall and shoulder seasons, gusts can reach 40 km/h or more. Booth setups need to stay stable without interrupting the experience. That's why placement and setup approach matter just as much as the booth itself." },
    { type: "h3", text: "Keeps Guests Engaged Between Moments" },
    { type: "p", text: "Even the best events have slower points. People step away, grab drinks, or take in the view. A photo booth gives them something to come back to. It keeps interaction going without forcing anything." },
    { type: "h3", text: "Creates Shareable Content in a Unique Setting" },
    { type: "p", text: "Photos and videos taken in Canmore don't just capture people. They capture the environment. Mountain views, outdoor light, and natural surroundings add something you don't get anywhere else. That makes the content more likely to be shared and remembered." },
    { type: "h2", text: "Your Canmore Photo Booth Lineup" },
    { type: "p", text: "Every event in Canmore is a little different. The booth should match that." },
    { type: "h3", text: "Pole Photo Booth in Canmore" },
    { type: "p", text: "The pole booth is compact and flexible. It works well for smaller venues, indoor halls like Legion Hall, trailhead tents, and birthday events. It doesn't take up much space and keeps things moving. It's a good fit for events where layout is tight or constantly changing." },
    { type: "h3", text: "Canmore 360 Photo Booth" },
    { type: "p", text: "The 360 booth adds movement and energy. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It works well for weddings, festivals, corporate retreats, and group-focused events. You'll often see it placed near the main activity area so guests can jump in easily. At events like the Canmore Folk Music Festival, it fits naturally with the energy of the crowd and the setting." },
    { type: "h3", text: "Canmore Mirror Photo Booth" },
    { type: "p", text: "The mirror booth offers a more refined experience. Guests step in front of the mirror and take photos in a way that feels natural and simple. It's a strong choice for weddings, indoor receptions, showers, and events at venues like Elevation Place. It adds a more polished look without making things complicated." },
    { type: "h3", text: "Canmore Premium Photo Booth" },
    { type: "p", text: "The premium booth focuses on quality and flexibility. It's an open setup that allows larger group photos, consistent lighting, and clean high-quality images. This works well for weddings, corporate events, larger gatherings, and outdoor ceremonies at places like the Nordic Centre. It's a reliable option when image quality matters." },
    { type: "h3", text: "Canmore Audio Guest Book" },
    { type: "p", text: "Photos show what the event looked like. Audio captures what people said. The audio guest book lets guests leave voice messages using a phone-style setup. It's a strong addition for weddings, corporate retreats, and family gatherings. It gives you something to come back to later that photos alone don't capture." },
    { type: "h3", text: "Canmore Premium Backdrops" },
    { type: "p", text: "Backdrops help tie everything together visually. In Canmore, they often reflect the environment. Options can include pine forest styles, rocky ridge designs, and neutral tones that match mountain settings. They help keep photos consistent while still fitting the natural surroundings." },
    { type: "h2", text: "Perfect Canmore Events for Photo Booth Rentals" },
    { type: "p", text: "Photo booths work across all types of events in Canmore." },
    { type: "h3", text: "Canmore Wedding Photo Booth" },
    { type: "p", text: "Weddings in Canmore are often set in scenic outdoor locations or smaller indoor venues. A photo booth captures moments throughout the entire event, especially during transitions between ceremony and reception. Locations like the Canmore Legion Hall or Nordic Centre are common spots where booths fit naturally into the flow." },
    { type: "h3", text: "Corporate Retreats in Canmore" },
    { type: "p", text: "Canmore is a popular location for corporate retreats. Teams come out for a mix of work and downtime. A photo booth helps break things up and creates something interactive without requiring structure. Boundary Ranch and similar locations are common for these types of events." },
    { type: "h3", text: "Canmore Festivals and Community Events" },
    { type: "p", text: "Events like the Canmore Folk Music Festival at Stu Pepper Park bring in large crowds over multiple days. The Canmore Winter Carnival also draws steady attendance with activities spread across the town. These events require setups that can handle continuous use and changing conditions." },
    { type: "h3", text: "Backyard Gatherings and Reunions in Canmore" },
    { type: "p", text: "Neighborhoods like Cougar Creek often host smaller, more personal events. Portable booth setups make it easy to bring the same experience into a backyard or private setting." },
    { type: "h2", text: "Canmore Venue Planning Guide" },
    { type: "p", text: "Planning an event in Canmore requires attention to detail." },
    { type: "h3", text: "Venue Coordination" },
    { type: "p", text: "Venues like Canmore Legion Hall, Elevation Place, and Canmore Nordic Centre all have different layouts and access points. Photo booths are typically set up ahead of your event, but timing can be adjusted based on your needs. Setup can also happen during the event if requested." },
    { type: "h3", text: "Outdoor Setup and Wind" },
    { type: "p", text: "Wind is one of the biggest factors in Canmore. Gusts can reach 40 km/h or more, especially in open areas or near trailheads. Placement and stability need to be planned properly to keep everything running smoothly." },
    { type: "h3", text: "Space Requirements" },
    { type: "p", text: "Most booths don't require a large footprint. Pole booth: about 6x6 ft. Larger setups: around 8x8 ft." },
    { type: "h3", text: "Positioning Tip" },
    { type: "p", text: "Placing the booth near high-traffic areas like drink stations or gathering points helps keep usage consistent. At events like the Folk Festival, placing it near beer tents or central areas helps keep a steady flow." },
    { type: "h2", text: "Why Canmore Events Choose Photobooth Experience" },
    { type: "p", text: "Events in Canmore are unique. The service needs to match the environment." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events need different setups. Having multiple booth types gives you flexibility." },
    { type: "h3", text: "Built for Mountain Conditions" },
    { type: "p", text: "Setups are designed to work in outdoor environments with wind and elevation." },
    { type: "h3", text: "Local Coverage Across Canmore" },
    { type: "p", text: "From downtown venues to residential neighborhoods like Cougar Creek, coverage is consistent across the area." },
    { type: "h3", text: "Easy Access to Photos and Videos" },
    { type: "p", text: "Guests can access their content after the event without extra steps." },
  ],
  faqs: [
    { q: "Is a 360 photo booth a good fit for the Canmore Folk Music Festival?", a: "Yes. It captures movement and energy from the crowd, creating content that guests enjoy sharing during multi-day events." },
    { q: "How does a mirror photo booth work at Canmore events?", a: "Guests stand in front of the mirror and take photos naturally. It's simple and works well for both indoor and outdoor setups." },
    { q: "Can photo booths handle wind at Canmore outdoor venues?", a: "Yes. Setups are planned with stability in mind to handle common wind conditions in the Bow Valley." },
    { q: "Why add an audio guest book to a Canmore retreat?", a: "It captures voice messages from guests, creating something more personal than photos alone." },
    { q: "Can backdrops match Canmore mountain events?", a: "Yes. Backdrops can reflect natural surroundings or event themes while keeping photos consistent." },
  ],
  image: "/locations/canmore.jpg",
  ctaSubtext: "If you're planning an event in Canmore and want something that keeps people engaged, photo booth rentals are one of the easiest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
