"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Crossfield",
  heroSubtitle: "Crossfield photo booth rentals for weddings, grads, and events. Reliable setups, multiple booth options, and seamless service.",
  introParagraphs: [
    "Crossfield photo booth rental services are built for events that bring together family, friends, and the local community.",
    "In Crossfield, events are simple, social, and personal. Whether it's a wedding in a community hall, a backyard celebration, or a grad ceremony at a local school, people show up to take part.",
    "That's where a photo booth fits in.",
    "It gives guests something to step into right away. No pressure, no complicated setup, just real moments captured naturally throughout the event.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Agricultural fairs",
    "Grad ceremonies",
    "Family reunions",
    "Corporate dinners",
  ],
  introClosure: "You can choose from pole booths, 360 booths, mirror booths, premium setups, audio guest books, and prairie-inspired backdrops. Everything is delivered and set up based on your event, with support so everything runs smoothly. Crossfield's seasonal weather plays a big role in event planning. The first heavy snow often arrives in early October, which shifts many events indoors earlier than expected.",
  contentBlocks: [
    { type: "h2", text: "Perfect for Crossfield's Indoor and Outdoor Events" },
    { type: "p", text: "Events in Crossfield often move between indoor and outdoor spaces depending on the season. A photo booth needs to work in both." },
    { type: "h3", text: "Keeps Guests Engaged Throughout the Event" },
    { type: "p", text: "Even well-planned events have slower moments. Guests move between spaces, grab food, or take breaks. A photo booth gives them something to return to. It keeps the energy consistent without forcing interaction." },
    { type: "h3", text: "Built for Seasonal Changes" },
    { type: "p", text: "Crossfield events deal with early October snowfall, September frost, chinook wind shifts, and summer storms. Photo booths need to be stable and adaptable to keep running smoothly." },
    { type: "h3", text: "Works Across Local Event Spaces" },
    { type: "p", text: "Most Crossfield events take place in community halls, school gymnasiums, backyard acreages, and banquet rooms and restaurants. Photo booths adapt easily to all of these environments." },
    { type: "h2", text: "Your Crossfield Booth Collection" },
    { type: "p", text: "Each booth option works differently depending on your event." },
    { type: "h3", text: "Space-Saving Pole Photo Booth in Crossfield" },
    { type: "p", text: "The pole booth is compact and efficient. It works well for community halls, school gyms, smaller gatherings, and backyard setups. It's easy to place and keeps the flow moving." },
    { type: "h3", text: "Crossfield 360 Photo Booth" },
    { type: "p", text: "The 360 booth adds movement and energy. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It's a strong fit for weddings, community events, backyard receptions, and agricultural celebrations. It works well in open layouts where guests can move freely." },
    { type: "h3", text: "Crossfield Mirror Photo Booth" },
    { type: "p", text: "The mirror booth offers a more refined experience. Guests stand in front of the mirror and take photos naturally. It fits well for weddings, showers, indoor receptions, and community events. It's simple to use and works in both large and small venues." },
    { type: "h3", text: "Crossfield Premium Photo Booth" },
    { type: "p", text: "The premium booth focuses on quality and flexibility. It allows larger group photos, consistent lighting, and high-quality images. This is ideal for weddings, larger gatherings, community events, and banquet-style receptions." },
    { type: "h3", text: "Crossfield Audio Guest Book" },
    { type: "p", text: "Photos show what happened. Audio captures what people said. The audio guest book allows guests to leave voice messages using a phone-style setup. It's a strong addition for weddings, family reunions, and grad ceremonies. It creates something meaningful you can revisit later." },
    { type: "h3", text: "Crossfield Premium Backdrops" },
    { type: "p", text: "Backdrops help define the look of your photos. In Crossfield, they often reflect prairie landscapes, golden canola fields, and sunset tones. They help create a consistent visual style." },
    { type: "h2", text: "Perfect Crossfield Events for Photo Booth Rentals" },
    { type: "p", text: "Photo booths work across all types of events in Crossfield." },
    { type: "h3", text: "Crossfield Wedding Photo Booth" },
    { type: "p", text: "Weddings in Crossfield often take place in community halls, backyard acreages, and rural venues. A photo booth captures moments throughout the entire event." },
    { type: "h3", text: "Grad Ceremonies in Crossfield" },
    { type: "p", text: "Grad events often take place in local school gymnasiums. Bleacher seating naturally directs students toward central areas, making photo booth placement simple." },
    { type: "h3", text: "Agricultural Fairs and Local Events" },
    { type: "p", text: "Crossfield has strong ties to agriculture. Events in the area often involve outdoor setups and large groups. Photo booths help keep guests engaged." },
    { type: "h3", text: "Family Reunions and Private Events" },
    { type: "p", text: "Backyard and rural gatherings are common. Photo booths provide an easy way to capture group moments." },
    { type: "h3", text: "Community Dinners and Banquet Events" },
    { type: "p", text: "Restaurants and banquet rooms host many local events. Photo booths can be set up easily where space allows." },
    { type: "h2", text: "Crossfield Venue Planning Guide" },
    { type: "p", text: "Planning in Crossfield requires attention to layout and timing." },
    { type: "h3", text: "Community Halls" },
    { type: "p", text: "Community halls often include gymnasium-style layouts, kitchen access, and open reception space. Guest flow typically moves from dining areas into central spaces." },
    { type: "h3", text: "Local Schools" },
    { type: "p", text: "School gymnasiums provide large open layouts, bleacher seating, and easy access from parking. They work well for grad ceremonies and large gatherings." },
    { type: "h3", text: "Private Residences and Acreages" },
    { type: "p", text: "Backyard events require clear space for setup and planning for outdoor conditions. Gravel driveways and open land are common." },
    { type: "h3", text: "Banquet Rooms and Restaurants" },
    { type: "p", text: "These venues typically require enough space for setup and coordination with dining layout. Kitchen proximity helps create natural flow from dining to photos." },
    { type: "h3", text: "Weather Considerations" },
    { type: "p", text: "Crossfield weather can change quickly. Early October snow shifts events indoors, chinook winds create rapid temperature changes, and summer storms can affect outdoor setups. Planning for flexibility is key." },
    { type: "h2", text: "Why Crossfield Locals Choose Photobooth Experience" },
    { type: "p", text: "Events in Crossfield require flexibility. The service needs to match the environment." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events need different setups. Having multiple booth types allows you to choose what fits best." },
    { type: "h3", text: "Built for Rural and Community Events" },
    { type: "p", text: "Crossfield events are local and personal. Everything is designed to feel easy and natural for guests." },
    { type: "h3", text: "Full Coverage Across Crossfield" },
    { type: "p", text: "We service all areas, including community spaces, schools, and rural properties." },
    { type: "h3", text: "Easy Access to Photos and Videos" },
    { type: "p", text: "Guests can access their content after the event without extra steps." },
  ],
  faqs: [
    { q: "Is a 360 photo booth a good fit for Crossfield backyard weddings?", a: "Yes. It captures movement and group interaction in open outdoor settings." },
    { q: "How does a mirror photo booth work at Crossfield events?", a: "Guests stand in front of the mirror and take photos naturally. It works well in both indoor and outdoor venues." },
    { q: "Can photo booths handle Crossfield weather conditions?", a: "Yes. Setups are designed to handle snow, wind, and temperature changes." },
    { q: "Why add an audio guest book to a Crossfield event?", a: "It captures voice messages from guests, creating something more personal than photos." },
    { q: "Can backdrops match Crossfield prairie themes?", a: "Yes. Backdrops can reflect prairie landscapes and event styles." },
  ],
  image: "/locations/Crossfield.jpg",
  ctaSubtext: "If you're planning an event in Crossfield and want something that keeps people engaged, photo booth rentals are one of the easiest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
