"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Nanton",
  heroSubtitle: "Nanton photo booth rentals for weddings, fundraisers, and events. Wind-ready setups, multiple booth options, and seamless service.",
  introParagraphs: [
    "Nanton photo booth rentals are built for events that blend prairie landscapes, heritage charm, and close-knit community gatherings.",
    "In Nanton, events feel intentional. Whether it's a garden wedding, a community fundraiser, or a family celebration, people come together to connect, not just attend.",
    "That's where a photo booth fits in.",
    "It gives guests something to step into right away. No pressure, no complicated setup, just natural moments captured throughout the event.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Community fundraisers",
    "Agricultural fairs",
    "Family reunions",
  ],
  introClosure: "You can choose from pole booths, 360 booths, mirror booths, premium setups, audio guest books, and prairie garden-inspired backdrops. Everything is delivered and set up based on your event, with support so everything runs smoothly. Nanton's weather conditions are a key part of planning. Chinook winds in the area can exceed 50 km/h, especially in open garden or rural venues, which means outdoor setups need to be stable and properly anchored.",
  contentBlocks: [
    { type: "h2", text: "Perfect for Nanton's Garden and Heritage Events" },
    { type: "p", text: "Events in Nanton often combine outdoor beauty with indoor practicality. You'll see garden ceremonies, heritage venues, community halls, and rural properties. A photo booth needs to work across all of them." },
    { type: "h3", text: "Keeps Guests Engaged Naturally" },
    { type: "p", text: "Events here are relaxed but social. Guests move between spaces, talk, and take part in different parts of the event. A photo booth gives them something to return to. It keeps the energy consistent without needing structure." },
    { type: "h3", text: "Built for Southern Alberta Weather" },
    { type: "p", text: "Nanton events deal with chinook winds over 50 km/h, summer hail storms, sudden temperature shifts, and early fall frost. Photo booth setups need to be stable and adaptable to keep running smoothly." },
    { type: "h3", text: "Fits Local Event Spaces" },
    { type: "p", text: "Most Nanton events take place in heritage venues, community centres, banquet halls, and rural properties. Photo booths adapt easily to these environments." },
    { type: "h2", text: "Your Nanton Booth Collection" },
    { type: "p", text: "Each booth option works differently depending on your event." },
    { type: "h3", text: "Garden-Ready Pole Photo Booth in Nanton" },
    { type: "p", text: "The pole booth is compact and easy to place. It works well for smaller venues, garden tents, community halls, and intimate gatherings. It fits easily into tighter layouts while keeping the flow moving." },
    { type: "h3", text: "Nanton 360 Photo Booth" },
    { type: "p", text: "The 360 booth adds movement and energy. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It's a strong fit for weddings, community events, garden receptions, and larger gatherings. It works well in open spaces where guests can move freely." },
    { type: "h3", text: "Nanton Mirror Photo Booth" },
    { type: "p", text: "The mirror booth offers a more refined experience. Guests stand in front of the mirror and take photos naturally. It fits well for weddings, family events, community gatherings, and indoor receptions. It's simple and works well in both heritage and modern venues." },
    { type: "h3", text: "Nanton Premium Photo Booth" },
    { type: "p", text: "The premium booth focuses on quality and flexibility. It allows larger group photos, consistent lighting, and high-quality images. This is ideal for weddings, fundraisers, larger receptions, and community events. It works well in venues that host bigger guest counts." },
    { type: "h3", text: "Nanton Audio Guest Book" },
    { type: "p", text: "Photos show what happened. Audio captures what people said. The audio guest book allows guests to leave voice messages using a phone-style setup. It's a strong addition for weddings, family reunions, and community gatherings. It creates something meaningful you can revisit after the event." },
    { type: "h3", text: "Nanton Premium Backdrops" },
    { type: "p", text: "Backdrops help define the look of your photos. In Nanton, they often reflect garden themes, prairie landscapes, and heritage settings. They help create a consistent visual style." },
    { type: "h2", text: "Perfect Nanton Events for Photo Booth Rentals" },
    { type: "p", text: "Photo booths work across all types of events in Nanton." },
    { type: "h3", text: "Nanton Garden Wedding Photo Booth" },
    { type: "p", text: "Garden weddings are common in Nanton, especially at heritage-style venues. A photo booth captures moments throughout the entire event, from ceremony to reception." },
    { type: "h3", text: "Community Fundraisers and Events" },
    { type: "p", text: "Spaces like the Nanton Community Centre host fundraisers and gatherings. Photo booths add something interactive without changing the structure of the event." },
    { type: "h3", text: "Heritage and Cultural Events" },
    { type: "p", text: "Locations like the Lions Den or Silver Willow Lodge host community programs and events. Photo booths help bring people together and capture those moments." },
    { type: "h3", text: "Agricultural Fairs and Local Celebrations" },
    { type: "p", text: "Nanton has strong ties to agriculture. Events in the area often involve outdoor setups and large groups. Photo booths help keep guests engaged throughout the day." },
    { type: "h3", text: "Family Reunions and Private Events" },
    { type: "p", text: "Banquet halls, restaurants, and rural properties are common for gatherings. Photo booths provide a simple way to capture group moments." },
    { type: "h2", text: "Nanton Venue-Specific Planning Guide" },
    { type: "p", text: "Planning in Nanton requires attention to both space and weather." },
    { type: "h3", text: "Heritage Venues" },
    { type: "p", text: "Locations like Coutts Centre-style properties include garden ceremony areas, pavilion-style reception spaces, and outdoor walking areas. These venues often combine indoor and outdoor setups." },
    { type: "h3", text: "Nanton Community Centre" },
    { type: "p", text: "This space offers a multi-level layout, kitchen access, and flexible event space. Guests often move naturally between areas." },
    { type: "h3", text: "Silver Willow Lodge" },
    { type: "p", text: "This venue is often used for indoor community events, multi-generational gatherings, and winter receptions. It provides a reliable indoor option when outdoor conditions change." },
    { type: "h3", text: "Rural Properties and Banquet Spaces" },
    { type: "p", text: "Many events take place on private land or in banquet halls. These setups often require stable placement on gravel and additional planning for outdoor conditions. Chinook winds can exceed 50 km/h, so proper anchoring is important." },
    { type: "h2", text: "Why Nanton Locals Choose Photobooth Experience" },
    { type: "p", text: "Events in Nanton require flexibility. The service needs to match the environment." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events need different setups. Having multiple booth types allows you to choose what fits best." },
    { type: "h3", text: "Built for Garden and Rural Events" },
    { type: "p", text: "Nanton events often combine outdoor and indoor elements. Everything is designed to work across both." },
    { type: "h3", text: "Full Coverage Across Nanton" },
    { type: "p", text: "We service the entire area, including rural properties and surrounding Foothills locations." },
    { type: "h3", text: "Easy Access to Photos and Videos" },
    { type: "p", text: "Guests can access their content after the event without extra steps." },
  ],
  faqs: [
    { q: "Is a 360 photo booth a good fit for Nanton garden weddings?", a: "Yes. It captures movement and group interaction in open outdoor settings." },
    { q: "How does a mirror photo booth work at Nanton events?", a: "Guests stand in front of the mirror and take photos naturally. It works well in both indoor and outdoor venues." },
    { q: "Can photo booths handle Nanton wind conditions?", a: "Yes. Setups are designed with stability in mind to handle chinook winds." },
    { q: "Why add an audio guest book to a Nanton event?", a: "It captures voice messages from guests, creating something more personal than photos." },
    { q: "Can backdrops match Nanton garden themes?", a: "Yes. Backdrops can reflect prairie and garden-style settings." },
  ],
  image: "/locations/nanton.jpg",
  ctaSubtext: "If you're planning an event in Nanton and want something that keeps people engaged, photo booth rentals are one of the easiest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
