"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Olds",
  heroSubtitle: "Olds photo booth rentals for weddings, grad ceremonies, and events. Reliable setups, multiple booth options, and seamless service.",
  introParagraphs: [
    "Olds photo booth rentals bring something interactive to events that are already built around community, family, and local traditions.",
    "In Olds, events feel connected. Whether it's a wedding at the Agriculture Society grounds, a grad ceremony at Olds College, or a local gathering, people show up to take part, not just watch.",
    "That's where a photo booth fits in.",
    "It gives guests something to step into right away. No waiting, no overthinking, just quick moments captured naturally as the event unfolds.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Agricultural shows",
    "Corporate meetings",
    "Grad ceremonies",
    "Family reunions",
  ],
  introClosure: "You can choose from pole booths, 360 booths, mirror booths, premium setups, audio guest books, and custom harvest-themed backdrops. Everything is delivered and set up based on your event, with support so everything runs smoothly. Olds events also come with changing weather conditions. Early snowfall can start as soon as October, and chinook winds can reach 40 km/h or more, which makes stable and adaptable setups important.",
  contentBlocks: [
    { type: "h2", text: "Elevate Olds Gatherings with Reliable Booths" },
    { type: "p", text: "Events in Olds often combine indoor and outdoor elements. Community halls, agricultural grounds, and open spaces all play a role. A photo booth needs to work across all of them." },
    { type: "h3", text: "Keeps Guests Engaged Throughout the Event" },
    { type: "p", text: "Even well-planned events have slower moments. People move between spaces, grab food, or take breaks. A photo booth gives them something to come back to. It keeps interaction going without forcing it." },
    { type: "h3", text: "Works in All Olds Event Environments" },
    { type: "p", text: "Olds events often happen in community halls, agricultural pavilions, outdoor arenas, and campus facilities. Photo booths adapt to all of these without requiring complex setup." },
    { type: "h3", text: "Captures Moments That Feel Local" },
    { type: "p", text: "Photos in Olds often reflect prairie sunsets, agricultural settings, and community spaces. A booth helps capture those moments naturally." },
    { type: "h2", text: "Your Olds Booth Collection" },
    { type: "p", text: "Every event is different. The booth should match the environment." },
    { type: "h3", text: "Compact Pole Photo Booth in Olds" },
    { type: "p", text: "The pole booth is simple and efficient. It works well for smaller venues, theatre lobbies, grad events, and corporate gatherings. It fits easily into tighter layouts like the Community Learning Campus lobby or smaller indoor spaces." },
    { type: "h3", text: "Olds 360 Photo Booth" },
    { type: "p", text: "The 360 booth adds movement and energy. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It's a strong fit for grad ceremonies, weddings, agricultural shows, and community events. It's often placed near the main activity area so guests can easily step in." },
    { type: "h3", text: "Olds Mirror Photo Booth" },
    { type: "p", text: "The mirror booth offers a more refined experience. Guests stand in front of the mirror and take photos naturally. It works well for weddings, indoor receptions, family events, and community gatherings. It's simple to use and doesn't require explanation." },
    { type: "h3", text: "Olds Premium Photo Booth" },
    { type: "p", text: "The premium booth focuses on quality and flexibility. It allows larger group photos, consistent lighting, and clean high-quality images. It works well for weddings, corporate events, larger gatherings, and campus events. It's a strong option for venues like the Olds College Event Centre where larger groups are common." },
    { type: "h3", text: "Olds Audio Guest Book" },
    { type: "p", text: "Photos show what happened. Audio captures what people said. The audio guest book allows guests to leave voice messages using a phone-style setup. It's a great addition for weddings, reunions, and grad celebrations. It gives you something to revisit after the event." },
    { type: "h3", text: "Olds Premium Backdrops" },
    { type: "p", text: "Backdrops help define how your photos look. In Olds, they often reflect harvest themes, prairie landscapes, and neutral tones. They help create a consistent look across all photos." },
    { type: "h2", text: "Perfect Olds Events for Photo Booth Rentals" },
    { type: "p", text: "Photo booths work across all types of events in Olds." },
    { type: "h3", text: "Olds Wedding Photo Booth" },
    { type: "p", text: "Weddings in Olds often take place at venues like the Olds Agriculture Society or Community Learning Campus. A photo booth captures moments throughout the event, from early arrivals to late-night interactions." },
    { type: "h3", text: "Olds Grad Photo Booth" },
    { type: "p", text: "Grad ceremonies are a major part of Olds events, especially at Olds College and local schools. A photo booth gives students and families a way to capture moments without needing formal setups." },
    { type: "h3", text: "Agricultural Shows and Events in Olds" },
    { type: "p", text: "Olds has a strong agricultural community. Events at the Ag Society grounds and outdoor arenas bring in large groups. Photo booths help keep guests engaged throughout the event." },
    { type: "h3", text: "Community Events and Festivals in Olds" },
    { type: "p", text: "Events like Kick It To The Curb and seasonal programming bring people together throughout the year. Photo booths provide an easy way to add something interactive without disrupting the flow." },
    { type: "h3", text: "Backyard Events and Family Reunions in Olds" },
    { type: "p", text: "Smaller gatherings are common in Olds. Portable booth setups make it easy to bring the same experience into a more relaxed environment." },
    { type: "h2", text: "Olds Venue-Specific Planning Guide" },
    { type: "p", text: "Planning in Olds requires attention to layout and timing." },
    { type: "h3", text: "Olds Agriculture Society Grounds" },
    { type: "p", text: "The main pavilion offers indoor space with power access, large capacity for events, and nearby parking. Outdoor arenas may require stable placement and base support depending on surface conditions." },
    { type: "h3", text: "Community Learning Campus" },
    { type: "p", text: "The Kiwanis Performing Arts Centre and surrounding areas provide indoor lobby space, easy access for setup, and flexible event layouts. Loading is typically done through the 50th Avenue service entrance." },
    { type: "h3", text: "Olds College Event Centre" },
    { type: "p", text: "This location offers direct parking access, indoor and outdoor options, and power access in multiple areas. It's a strong location for larger events and grad ceremonies." },
    { type: "h3", text: "Weather Considerations" },
    { type: "p", text: "Olds weather can change quickly. Early snowfall can begin in October, and chinook winds can reach 40 km/h or more. Planning for stable placement and temperature conditions is important for outdoor events." },
    { type: "h2", text: "Why Olds Locals Choose Photobooth Experience" },
    { type: "p", text: "Events in Olds require a flexible approach. The service needs to match the environment." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events need different setups. Having multiple options makes it easier to choose what fits best." },
    { type: "h3", text: "Built for Local Conditions" },
    { type: "p", text: "Olds events involve both indoor and outdoor setups. Everything is designed to work across both." },
    { type: "h3", text: "Full Coverage Across Olds" },
    { type: "p", text: "We service all areas of Olds and surrounding communities." },
    { type: "h3", text: "Easy Photo and Video Access" },
    { type: "p", text: "Guests can access their content after the event without extra steps." },
  ],
  faqs: [
    { q: "Is a 360 photo booth a good fit for Olds grad ceremonies?", a: "Yes. It captures movement and energy, making it ideal for large group celebrations." },
    { q: "How does a mirror photo booth work at Olds events?", a: "Guests stand in front of the mirror and take photos naturally. It works well for both formal and casual settings." },
    { q: "Can photo booths handle outdoor Olds events?", a: "Yes. Setups can be adjusted for outdoor conditions including wind and temperature changes." },
    { q: "Why add an audio guest book to an Olds event?", a: "It captures voice messages from guests, creating something more personal than photos." },
    { q: "Can backdrops match Olds agricultural themes?", a: "Yes. Backdrops can reflect harvest, prairie, or event-specific designs." },
  ],
  image: "/locations/olds.jpg",
  ctaSubtext: "If you're planning an event in Olds and want something that keeps people engaged, photo booth rentals are one of the easiest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
