"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Milo",
  heroSubtitle: "Milo photo booth rentals for weddings, farm events, and reunions. Portable setups, prairie-ready booths, and seamless service.",
  introParagraphs: [
    "Milo photo booth rental services are built for events that feel real, local, and deeply connected to prairie life.",
    "In Milo, events aren't about scale. They're about people. Family gatherings on quarter sections, barn weddings, community suppers, and agricultural fairs. Everything revolves around connection and shared experience.",
    "That's where a photo booth fits in.",
    "It gives guests something to step into right away. No pressure, no complicated setup, just real moments captured naturally as the event unfolds.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Agricultural fairs",
    "Community suppers",
    "Corporate gatherings",
    "Backyard family events and reunions",
  ],
  introClosure: "You can choose from pole booths, 360 booths, mirror booths, premium setups, audio guest books, and custom prairie-inspired backdrops. Everything is delivered and set up based on your event, with support so it runs smoothly anywhere, including remote farm properties. Milo is a small prairie village of about 155 residents, located southeast of Calgary in Vulcan County, where grain farming drives both the economy and local event culture.",
  contentBlocks: [
    { type: "h2", text: "Why Milo Events Need Prairie-Ready Photo Booths" },
    { type: "p", text: "Events in Milo aren't like city events. They're often on private land, spread across large farm properties, affected by wind and dust, and multi-generational. A photo booth needs to work within that environment." },
    { type: "h3", text: "Built for Gravel Roads and Remote Access" },
    { type: "p", text: "Many events in Milo happen on quarter sections. That means gravel roads, long driveways, and limited infrastructure. Photo booth setups need to be portable and easy to transport without affecting performance." },
    { type: "h3", text: "Handles Dust and Prairie Wind" },
    { type: "p", text: "Milo sees around 110 windy days per year, and dust is common during harvest season. That creates unique challenges for outdoor events. Photo booths need to stay stable and protected so they continue running without interruption." },
    { type: "h3", text: "Works Without Reliable Cell Service" },
    { type: "p", text: "Rural events often deal with limited connectivity. Offline capture with digital gallery access later ensures guests can still receive and share their photos." },
    { type: "h3", text: "Designed for Multi-Generational Events" },
    { type: "p", text: "Milo events often include kids, parents, grandparents, and extended family. A photo booth is one of the few things everyone can participate in together." },
    { type: "h2", text: "Photo Booth Types Built for Milo's Country Lifestyle" },
    { type: "p", text: "Each booth fits a different type of event." },
    { type: "h3", text: "Pole Photo Booth for Farm Weddings in Milo" },
    { type: "p", text: "The pole booth is lightweight and easy to transport. It works well for acreage weddings, backyard reunions, and farm gatherings. It's ideal for setups along Township Road 200 or other rural properties where access varies." },
    { type: "h3", text: "360 Photo Booth Milo Alberta" },
    { type: "p", text: "The 360 booth adds movement and energy. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It's a strong fit for agricultural fairs, birthday parties, larger gatherings, and community events. It works especially well at the Milo Agricultural Society Fair, where crowds gather for events like tractor pulls and cattle shows." },
    { type: "h3", text: "Mirror Photo Booth Milo" },
    { type: "p", text: "The mirror booth offers a more refined experience. Guests stand in front of the mirror and take photos naturally. It works well for weddings, community suppers, indoor receptions, and corporate gatherings. It fits well in spaces like the Milo Community Hall." },
    { type: "h3", text: "Premium Backdrops & Audio Guest Books" },
    { type: "p", text: "Premium features bring more depth to the experience. Backdrops can reflect golden wheat fields, canola crops, prairie skies, and grain elevator silhouettes. Audio guest books allow guests to leave voice messages, making them a strong addition for weddings, milestone birthdays, and family gatherings." },
    { type: "h2", text: "Top Milo Venues for Reliable Photo Booth Setups" },
    { type: "p", text: "Photo booths can be set up almost anywhere in Milo. Here's how they fit into local venues." },
    { type: "h3", text: "Milo Community Hall" },
    { type: "p", text: "Best for weddings, community suppers, and corporate events. Capacity around 120 seated, indoor space with reliable power, and hosts over 50 events annually." },
    { type: "h3", text: "Milo Agricultural Society Grounds" },
    { type: "p", text: "Best for fairs, tractor pulls, and outdoor events. Large outdoor space with indoor and outdoor flexibility and multiple major events each year." },
    { type: "h3", text: "Private Farm Quarter-Sections" },
    { type: "p", text: "Best for barn weddings, family reunions, and backyard gatherings. Open prairie space with natural amphitheatre layouts and flexible setup areas." },
    { type: "h3", text: "Milo School Gymnasium" },
    { type: "p", text: "Best for birthday parties, baby showers, and community events. Indoor space with reliable facilities and easy access." },
    { type: "h2", text: "Milo Event Timing & Prairie Weather Strategy" },
    { type: "p", text: "Planning in Milo requires understanding the seasons." },
    { type: "h3", text: "Harvest and Fair Season" },
    { type: "p", text: "Late August to early September is peak event time. Events like the Milo Agricultural Society Fair bring in large crowds. Around 85 percent of events during this period can stay outdoors." },
    { type: "h3", text: "Summer Events" },
    { type: "p", text: "July and August offer average highs around 24°C, dry conditions, and strong outdoor event viability. Pole and 360 booths perform best during this time." },
    { type: "h3", text: "Winter Conditions" },
    { type: "p", text: "Winter brings temperatures down to -30°C and limited outdoor activity. Indoor setups become the focus." },
    { type: "h3", text: "Dust and Wind Considerations" },
    { type: "p", text: "Milo sees 110 windy days annually, dust during harvest season, and around 200 mm of annual precipitation. Planning for wind and dust is essential for outdoor events." },
    { type: "h3", text: "Backdrop Selection" },
    { type: "p", text: "Local themes work best. Backdrops inspired by grain elevators, prairie roads, and wheat and canola fields create a stronger connection to the setting." },
    { type: "h2", text: "Why Milo Locals Choose Photobooth Experience" },
    { type: "p", text: "Events in Milo require a practical approach." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events need different setups. Having options makes it easier to match the event." },
    { type: "h3", text: "Built for Prairie Conditions" },
    { type: "p", text: "Wind, dust, and remote locations all play a role. Setups are designed to handle those conditions." },
    { type: "h3", text: "Full Coverage Across Milo" },
    { type: "p", text: "We service all areas, including remote farmsteads and surrounding rural communities." },
    { type: "h3", text: "Easy Access to Photos and Videos" },
    { type: "p", text: "Guests can access their content after the event without extra steps." },
  ],
  faqs: [
    { q: "Milo wedding photo booth rental — best setup?", a: "Mirror booths work well for Community Hall receptions and indoor weddings." },
    { q: "360 photo booth rental Milo for agricultural fairs?", a: "Yes. 360 booths capture movement and energy at events like the Milo Ag Society Fair." },
    { q: "Photo booth for baby showers Milo — best option?", a: "Audio guest books are a popular choice for capturing personal messages." },
    { q: "Backyard photo booth rental Milo on farm properties?", a: "Pole booths are portable and ideal for quarter-section setups." },
    { q: "Corporate photo booth Milo for co-op meetings?", a: "Premium setups with custom backdrops work well for Community Hall events." },
    { q: "Mirror photo booth rental Milo for birthdays?", a: "Yes. Mirror booths provide interactive experiences for all age groups." },
    { q: "Outdoor photo booth rental Milo during harvest season?", a: "Yes. Booths are designed to handle wind and dust conditions." },
    { q: "Gender reveal photo booth Milo ideas?", a: "360 booths with prairie-themed backdrops create strong visual moments." },
    { q: "Family reunion photo booth rental Milo options?", a: "Portable setups work well for large farm gatherings." },
    { q: "What farm scenery inspires Milo photo booth backdrops?", a: "Grain elevators, canola fields, and prairie roads are common themes." },
  ],
  image: "/locations/milo.jpg",
  ctaSubtext: "If you're planning an event in Milo and want something that keeps people engaged while fitting the environment, photo booth rentals are one of the easiest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
