"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Vulcan",
  heroSubtitle: "Vulcan photo booth rentals for weddings, festivals, and backyard events. Prairie-ready setups, multiple booth options, and seamless service.",
  introParagraphs: [
    "Vulcan photo booth rental services are built for events that feel local, social, and rooted in prairie life.",
    "In Vulcan, events are about people. Whether it's a wedding at the community hall, a summer fair at the ag grounds, or a backyard reunion on an acreage, the focus is always the same. Bring everyone together and make it count.",
    "That's where a photo booth fits in.",
    "It gives guests something to step into right away. No pressure, no waiting, just real moments captured as they happen.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Festivals and fairs",
    "Corporate events",
    "Backyard family gatherings",
    "Reunions",
  ],
  introClosure: "You can choose from pole booths, 360 booths, mirror booths, premium setups, audio guest books, and custom prairie-themed backdrops. Everything is delivered, set up based on your event, and supported so it runs smoothly anywhere. Vulcan is a small prairie town of about 1,850 people, located between Calgary and Lethbridge, with a strong agricultural community that drives local events year-round.",
  contentBlocks: [
    { type: "h2", text: "Benefits of Photo Booth Rental in Vulcan" },
    { type: "p", text: "Events in Vulcan are smaller, but that's exactly why interaction matters more." },
    { type: "h3", text: "Keeps Guests Engaged at Local Gatherings" },
    { type: "p", text: "At smaller events, you need something that gets people involved quickly. A photo booth does that without effort. Guests step in, take photos, and bring others with them." },
    { type: "h3", text: "Works in Indoor and Outdoor Spaces" },
    { type: "p", text: "Vulcan events often take place in community halls, legion halls, agricultural grounds, and private acreages. Photo booths can adapt to all of these environments." },
    { type: "h3", text: "Built for Prairie Weather" },
    { type: "p", text: "Vulcan has a semi-arid climate. You're dealing with summer highs around 24°C, windy conditions, and dry air and dust. Photo booth setups need to be stable and adaptable for both indoor and outdoor use." },
    { type: "h3", text: "Creates Shareable Content Anywhere" },
    { type: "p", text: "Even in rural settings, guests want to share their experience. Digital galleries make it easy for guests to access and post their photos right after the event." },
    { type: "h2", text: "Photo Booth Options for Vulcan Events" },
    { type: "p", text: "Each booth works differently depending on your event." },
    { type: "h3", text: "Pole Photo Booth for Backyard Events in Vulcan" },
    { type: "p", text: "The pole booth is compact and portable. It works well for backyard reunions, acreage weddings, and casual gatherings. It's easy to set up in open prairie spaces and doesn't take up much room." },
    { type: "h3", text: "360 Photo Booth Vulcan" },
    { type: "p", text: "The 360 booth adds movement and energy. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It's a strong fit for festivals, summer fairs, birthday parties, and large gatherings. It works especially well at events held at the Vulcan Ag Grounds where space allows for group interaction." },
    { type: "h3", text: "Mirror Photo Booth Vulcan" },
    { type: "p", text: "The mirror booth offers a more refined experience. Guests stand in front of the mirror and take photos naturally. It works well for weddings, indoor receptions, corporate events, and showers. It's simple to use and fits well in indoor venues." },
    { type: "h3", text: "Premium Features: Backdrops & Audio Guest Books" },
    { type: "p", text: "Premium setups allow larger group photos, consistent lighting, and high-quality images. Backdrops can reflect prairie landscapes, agricultural themes, and neutral tones for formal events. Audio guest books capture voice messages, making them a strong addition for weddings, baby showers, and reunions." },
    { type: "h2", text: "Best Vulcan Venues for Photo Booth Setups" },
    { type: "p", text: "Photo booths can be set up almost anywhere in Vulcan. Here's how they fit into local venues." },
    { type: "h3", text: "Agricultural Grounds" },
    { type: "p", text: "The Vulcan Ag Grounds is best for festivals, demolition derbies, and summer events. Indoor and outdoor flexibility combined with open space for high traffic makes this an ideal location." },
    { type: "h3", text: "Community Halls" },
    { type: "p", text: "The Vulcan Community Hall is best for weddings, baby showers, and reunions. Indoor space with flexible layouts allows easy flow from dining to photos." },
    { type: "h3", text: "Legion Halls" },
    { type: "p", text: "Local legion facilities are best for corporate events, birthday parties, and community gatherings. Reliable indoor space with consistent guest movement makes these setups straightforward." },
    { type: "h3", text: "Rural Acreages" },
    { type: "p", text: "Properties along Highway 23 are best for backyard weddings, family reunions, and private events. Open space placement adaptable to outdoor conditions makes rural setups possible." },
    { type: "h3", text: "Arena and Multi-Use Spaces" },
    { type: "p", text: "The Vulcan Arena is best for banquets, community events, and large gatherings. Its open layout and high capacity make it versatile." },
    { type: "h2", text: "Planning Your Vulcan Event with a Photo Booth" },
    { type: "p", text: "Planning in Vulcan comes down to flexibility." },
    { type: "h3", text: "Match Booth Type to Event Energy" },
    { type: "p", text: "360 booths work best for high-energy summer events. Mirror booths suit indoor weddings and formal receptions. Pole booths fit backyard and casual gatherings best." },
    { type: "h3", text: "Consider Indoor Backup Options" },
    { type: "p", text: "Prairie weather can change quickly. Indoor options are often used as backup for outdoor events." },
    { type: "h3", text: "Choose Backdrops That Fit the Setting" },
    { type: "p", text: "Local themes work best. Prairie and agricultural-inspired backdrops help photos feel connected to the event." },
    { type: "h3", text: "Book Early for Summer Events" },
    { type: "p", text: "Peak times include summer fairs, community events, and wedding season. Booking ahead helps secure your preferred setup." },
    { type: "h2", text: "Why Vulcan Locals Choose Photobooth Experience" },
    { type: "p", text: "Events in Vulcan require a practical approach." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events need different setups. Having options makes it easier to choose what fits best." },
    { type: "h3", text: "Built for Prairie Conditions" },
    { type: "p", text: "Wind, dust, and open spaces are part of the environment. Setups are designed to handle those conditions." },
    { type: "h3", text: "Full Coverage Across Vulcan" },
    { type: "p", text: "We service all areas, including community venues and rural acreages." },
    { type: "h3", text: "Easy Photo and Video Access" },
    { type: "p", text: "Guests can access their content after the event without extra steps." },
  ],
  faqs: [
    { q: "What types of events work best with Vulcan photo booth rental?", a: "Weddings, baby showers, birthdays, gender reveals, festivals, corporate events, backyard parties, and reunions all work well." },
    { q: "Vulcan wedding photo booth rental: which booth is best?", a: "Mirror booths are a strong option for indoor receptions and community hall weddings." },
    { q: "Can I get 360 photo booth rental in Vulcan for festivals?", a: "Yes. 360 booths work well for high-energy events at ag grounds and summer fairs." },
    { q: "Is photo booth rental available for baby showers in Vulcan?", a: "Yes. Audio guest books are a popular option for capturing messages at showers." },
    { q: "What about backyard photo booth rental in Vulcan?", a: "Pole booths are portable and ideal for acreage setups." },
    { q: "Corporate photo booth rental Vulcan options?", a: "Premium setups with custom backdrops work well for corporate events in halls or arenas." },
    { q: "Does Vulcan photo booth rental work outdoors?", a: "Yes. Portable booths are designed to handle prairie wind and open environments." },
    { q: "Mirror photo booth Vulcan for gender reveals?", a: "Yes. Mirror booths with custom backdrops work well for reveal moments." },
    { q: "Photo booth for birthday parties in Vulcan?", a: "360 booths are popular for creating fun, shareable content at birthday events." },
    { q: "How do premium backdrops enhance Vulcan events?", a: "They add local prairie themes and create a consistent look across all photos." },
  ],
  image: "/locations/vulcan.jpg",
  ctaSubtext: "If you're planning an event in Vulcan and want something that keeps people engaged, photo booth rentals are one of the easiest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
