"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Strathmore",
  heroSubtitle: "Strathmore photo booth rentals for weddings, rodeos, and events. Multiple booth options, easy setup, and engaging guest experiences.",
  introParagraphs: [
    "Strathmore photo booth rentals bring a different kind of energy to events that already feel grounded in community, family, and local traditions.",
    "Events in Strathmore are built around connection. Whether it's a wedding at the Ag Centre, a backyard barbecue, or a large gathering during Stampede season, people show up ready to take part.",
    "That's where a photo booth fits in.",
    "It gives guests something to step into right away. No waiting, no pressure. Just a quick way to capture moments as they happen.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Rodeos and festivals",
    "Corporate events",
    "Backyard gatherings and family reunions",
  ],
  introClosure: "You can choose from pole booths, 360 booths, mirror booths, premium setups, audio guest books, and custom backdrops. Everything is delivered and set up based on your event, with support so everything runs smoothly. With a population of around 14,000, Strathmore has a strong local event culture, and adding a photo booth can increase engagement by up to 50 percent at community gatherings.",
  contentBlocks: [
    { type: "h2", text: "Boost Strathmore Parties with Booth Energy" },
    { type: "p", text: "Events in Strathmore tend to be busy, social, and spread out across different spaces. A photo booth helps keep everything connected." },
    { type: "h3", text: "Keeps Lines Moving and Guests Engaged" },
    { type: "p", text: "At larger events, especially weddings and rodeos, people don't want to wait around. Photo booths help reduce downtime and keep things moving. At busy receptions, booths can cut wait times by up to 70 percent by giving guests something to do throughout the event." },
    { type: "h3", text: "Creates Shareable Moments" },
    { type: "p", text: "Photos and videos don't stay at the event. Guests share them. Events that include booths often see up to three times more reach online, especially when people tag local scenery or recognizable spots around Strathmore." },
    { type: "h3", text: "Built for Indoor and Outdoor Events" },
    { type: "p", text: "Strathmore events often take place in indoor arenas, community halls, outdoor fields, and ranch properties. Photo booths are flexible enough to work in all of these environments." },
    { type: "h2", text: "Strathmore's Go-To Booth Selection" },
    { type: "p", text: "Different events need different setups. Here's how each option fits Strathmore events." },
    { type: "h3", text: "Efficient Pole Photo Booth in Strathmore" },
    { type: "p", text: "The pole booth is compact and fast. It works well for smaller venues, birthday parties, corporate meetups, and events with limited space. Guests can move in and out quickly, keeping the flow steady. Pole booths are used in about 65 percent of compact rural venues because they fit easily into tighter spaces." },
    { type: "h3", text: "Strathmore 360 Photo Booth" },
    { type: "p", text: "The 360 booth adds movement and energy. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It's a strong fit for rodeos, festivals, weddings, and high-energy gatherings. It's often placed near the main activity area so guests can jump in easily. At farm and outdoor events, 360 content can generate up to seven times more engagement compared to standard formats." },
    { type: "h3", text: "Strathmore Mirror Photo Booth" },
    { type: "p", text: "The mirror booth offers a more polished experience. Guests stand in front of the mirror and take photos naturally. It works well for weddings, showers, indoor receptions, and formal gatherings. It's simple to use and draws attention without needing instructions. Participation can increase by around 42 percent, especially at community events and fairs." },
    { type: "h3", text: "Strathmore Premium Photo Booth" },
    { type: "p", text: "The premium booth focuses on quality and consistency. It's an open setup that allows larger group photos, clean lighting, and high-quality images. Best suited for weddings, corporate events, large gatherings, and community events. Premium booths are used in about 80 percent of weddings in the area because of their reliability and results." },
    { type: "h3", text: "Strathmore Audio Guest Book" },
    { type: "p", text: "Photos capture what the event looked like. Audio captures what people said and felt. The audio guest book allows guests to leave voice messages using a phone-style setup. It's a strong addition for weddings, reunions, and milestone events. Around 90 percent of couples go back and listen to these recordings within the first year." },
    { type: "h3", text: "Strathmore Premium Backdrops" },
    { type: "p", text: "Backdrops shape the look of every photo. They can match event themes, colors, branding, and venue style. Custom backdrops are used in about 85 percent of Strathmore events to create a consistent look across photos." },
    { type: "h2", text: "Strathmore Event Matches for Photo Booth Rentals" },
    { type: "p", text: "Photo booths work across all types of events in Strathmore." },
    { type: "h3", text: "Strathmore Wedding Photo Booth" },
    { type: "p", text: "Weddings in Strathmore often take place in community venues or rural properties. A photo booth captures moments throughout the entire event, from early arrivals to late-night interactions." },
    { type: "h3", text: "Baby Showers and Gender Reveals in Strathmore" },
    { type: "p", text: "These events focus on reactions and shared moments. A booth helps capture those moments naturally." },
    { type: "h3", text: "Strathmore Birthday Parties" },
    { type: "p", text: "Birthday events are simple and social. A photo booth gives guests something to do right away." },
    { type: "h3", text: "Strathmore Corporate Photo Booth" },
    { type: "p", text: "Corporate events in Strathmore are often tied to local businesses or community organizations. Photo booths help create interaction and provide content that can be used afterward." },
    { type: "h3", text: "Strathmore Rodeos and Festivals" },
    { type: "p", text: "Strathmore hosts large events like the Strathmore Stampede, which runs for 10 days and brings in over 20,000 attendees. Events like this require booths that can handle constant use and high traffic. The Wheatland County Fair also draws thousands of attendees and is another strong fit for high-capacity booth setups." },
    { type: "h3", text: "Backyard Events and Reunions in Strathmore" },
    { type: "p", text: "Backyard gatherings are common in Strathmore. Portable booth setups make it easy to bring the same experience into more relaxed environments." },
    { type: "h2", text: "Strathmore Setup Smarts" },
    { type: "p", text: "Planning in Strathmore requires a few practical considerations." },
    { type: "h3", text: "Venue Coordination" },
    { type: "p", text: "Locations like the Strathmore Ag Centre or Kinplex may require coordination for placement and access. Photo booths are typically set up ahead of your event, but timing can be adjusted based on your needs. Setup can also be done during the event if requested." },
    { type: "h3", text: "Outdoor Conditions" },
    { type: "p", text: "Strathmore events often deal with open fields and changing weather. Wind and dust should be considered when planning placement. Around 60 percent of events in the area deal with these conditions, making stable setups important." },
    { type: "h3", text: "Space Requirements" },
    { type: "p", text: "Most booths don't require a large footprint. Pole booth: about 6x6 ft. Larger setups: around 8x8 ft." },
    { type: "h3", text: "Booking Timeline" },
    { type: "p", text: "Busy seasons like Stampede fill up quickly. Most bookings happen about 4 to 6 weeks in advance." },
    { type: "h2", text: "Why Locals Choose Photobooth Experience in Strathmore" },
    { type: "p", text: "There are fewer providers in Strathmore compared to larger cities. That makes reliability and flexibility more important." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events need different setups. Having multiple booth types gives you the flexibility to choose what works best." },
    { type: "h3", text: "Built for Rural and Community Events" },
    { type: "p", text: "Strathmore events are unique. The setup needs to match the environment, whether that's indoors or outdoors." },
    { type: "h3", text: "Full Coverage Across Strathmore" },
    { type: "p", text: "We service both town locations and surrounding areas in Wheatland County." },
    { type: "h3", text: "Easy Access to Photos and Videos" },
    { type: "p", text: "Guests can access their content after the event without extra steps. Simple and straightforward." },
  ],
  faqs: [
    { q: "Is a 360 photo booth a good fit for Strathmore Stampede events?", a: "Yes. It captures dynamic video that works well for large crowds and high-energy environments." },
    { q: "How does a mirror photo booth work at Strathmore events?", a: "Guests stand in front of the mirror and take photos naturally. It's simple and works for both casual and formal setups." },
    { q: "Can photo booths handle outdoor Strathmore events?", a: "Yes. Setups can be adjusted for outdoor environments, including fields and ranch properties." },
    { q: "Why add an audio guest book to a Strathmore event?", a: "It captures voice messages from guests, creating something more personal than photos alone." },
    { q: "Can backdrops be customized for Strathmore corporate events?", a: "Yes. Backdrops can match branding, colors, and themes." },
    { q: "How much space is needed for a pole photo booth in Strathmore?", a: "About 6x6 ft is enough, making it ideal for smaller venues." },
    { q: "Are photo booths suitable for large Strathmore festivals?", a: "Yes. High-capacity setups can handle thousands of interactions across large events." },
    { q: "What events work best with a premium photo booth in Strathmore?", a: "Weddings, corporate events, and large gatherings benefit the most from higher-quality images and flexibility." },
    { q: "How is setup handled for Strathmore photo booth rentals?", a: "Setup is coordinated based on your venue and event schedule. It's usually done ahead of time but can be adjusted if needed." },
    { q: "Can the same booth work for different Strathmore event types?", a: "Yes. Booths can be customized with different overlays, templates, and backdrops." },
  ],
  image: "/locations/Strathmore.jpg",
  ctaSubtext: "If you're planning an event in Strathmore and want something that keeps people engaged, photo booth rentals are one of the easiest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
