"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Cochrane",
  heroSubtitle: "Cochrane photo booth rentals for weddings, parties, and festivals. Multiple booth options, easy setup, and memorable guest experiences.",
  introParagraphs: [
    "Cochrane photo booth rentals bring something extra to events that already feel personal and connected.",
    "Cochrane has a different pace compared to larger cities. Events here are often built around family, community, and shared experiences. Whether it's a wedding near the foothills, a backyard reunion, or a local festival, people show up to be part of it.",
    "That's exactly where a photo booth fits in.",
    "It gives guests something to do without overcomplicating things. They step in, interact, and create moments that feel natural instead of staged.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Corporate events",
    "Festivals and community events",
    "Backyard gatherings and family reunions",
  ],
  introClosure: "You can choose from pole booths, 360 video booths, mirror booths, premium setups, audio guest books, and custom backdrops. Everything is delivered, set up around your event schedule, and supported so it runs smoothly. Cochrane's population of over 35,000 supports a steady flow of community events, and adding a photo booth can increase guest interaction by up to 50%.",
  contentBlocks: [
    { type: "h2", text: "Elevate Cochrane Events with Photo Booth Fun" },
    { type: "p", text: "Events in Cochrane often blend two styles. You'll see formal setups inside venues and more relaxed outdoor gatherings, sometimes at the same event. A photo booth fits both without needing to change anything." },
    { type: "h3", text: "Keeps Guests Involved" },
    { type: "p", text: "Guests don't need direction. They see the booth, walk over, and start interacting. That's why event feedback shows photo booths can reduce downtime by up to 65%, especially during slower parts of the event like cocktail hour." },
    { type: "h3", text: "Creates Shareable Moments" },
    { type: "p", text: "Photos and videos don't stay at the event. They get shared. Cochrane events often see about 2.5 times more social reach when booths are included, especially when guests tag local areas or outdoor settings." },
    { type: "h3", text: "Matches Cochrane's Event Style" },
    { type: "p", text: "Cochrane events often combine indoor venues, outdoor spaces, and ranch or foothills settings. Photo booths adapt to all of them. They don't require a complicated setup and can be placed wherever it makes the most sense for your event." },
    { type: "h2", text: "Our Cochrane Photo Booth Collection" },
    { type: "p", text: "Every event is different. The booth should match it." },
    { type: "h3", text: "Pole Photo Booth in Cochrane" },
    { type: "p", text: "The pole booth is built for simplicity. It's compact, quick, and easy to place. Best for smaller venues, birthday parties, corporate events, and spaces with limited room. It allows guests to move in and out quickly, which keeps the flow going. About 55% of compact venues use this type of setup because it fits easily into tighter layouts." },
    { type: "h3", text: "Cochrane 360 Photo Booth" },
    { type: "p", text: "The 360 booth adds movement and energy. Instead of photos, it creates slow-motion video as the camera rotates around guests. It works well for weddings, festivals, high-energy events, and group-focused celebrations. It's often placed near the main activity area so guests can easily jump in. 360 booths can generate up to six times more social shares at outdoor events, especially when capturing group moments." },
    { type: "h3", text: "Cochrane Mirror Photo Booth" },
    { type: "p", text: "The mirror booth feels more refined. Guests step in front of the mirror and take photos in a way that feels natural and intuitive. It fits well for weddings, gender reveals, formal events, and indoor venues. It draws attention without needing explanation. Participation often increases because people are naturally curious and want to try it." },
    { type: "h3", text: "Cochrane Premium Photo Booth" },
    { type: "p", text: "The premium booth focuses on image quality and flexibility. It's an open setup that allows larger group photos, consistent lighting, and clean high-quality results. Best for weddings, corporate events, community gatherings, and milestone celebrations. Premium setups are used in about 75% of milestone events locally because of their consistency and quality." },
    { type: "h3", text: "Cochrane Audio Guest Book" },
    { type: "p", text: "Photos show what the event looked like. Audio shows what people felt. The audio guest book allows guests to leave voice messages using a phone-style setup. It works well for weddings, family reunions, and baby showers. Around 88% of people go back and listen to these messages within the first year." },
    { type: "h3", text: "Cochrane Premium Backdrops" },
    { type: "p", text: "The backdrop shapes how every photo looks. It sets the tone and ties everything together. Backdrops can match event themes, colors, branding, and venue style. Custom backdrops are used in about 82% of local events to create a consistent look across all photos." },
    { type: "h2", text: "Perfect Cochrane Events for Photo Booth Rentals" },
    { type: "p", text: "Photo booths work across all types of events in Cochrane." },
    { type: "h3", text: "Cochrane Wedding Photo Booth" },
    { type: "p", text: "Weddings in Cochrane often combine indoor and outdoor settings. A photo booth captures moments throughout the entire event, from early interactions to late-night energy. Venues like the Cochrane RancheHouse are popular spots where booths naturally fit into the layout." },
    { type: "h3", text: "Baby Showers and Gender Reveals in Cochrane" },
    { type: "p", text: "These events are built around reactions. A booth helps capture those reactions without making it feel staged. Props and backdrops add to the experience without overcomplicating it." },
    { type: "h3", text: "Cochrane Birthday Parties" },
    { type: "p", text: "Birthday events are about keeping things simple and fun. A photo booth gives guests something to do immediately. It works well for both kids and adults." },
    { type: "h3", text: "Cochrane Corporate Photo Booth" },
    { type: "p", text: "Corporate events in Cochrane are often smaller and more personal. Photo booths help create interaction and provide content that can be used afterward. Custom backdrops can also align with branding." },
    { type: "h3", text: "Cochrane Festivals and Community Events" },
    { type: "p", text: "Cochrane hosts events like the Spring Chicken Festival and Highland Games, which draw thousands of attendees. Spring Chicken Festival brings in over 5,000 people, while Highland Games attract between 10,000 and 15,000 visitors. These events require booths that can handle constant use and large crowds." },
    { type: "h3", text: "Backyard Events and Reunions in Cochrane" },
    { type: "p", text: "Backyard events are common in Cochrane. Portable setups make it easy to bring a booth into a more relaxed setting. No complicated logistics needed." },
    { type: "h2", text: "Cochrane Venue Planning Tips" },
    { type: "p", text: "Planning an event in Cochrane comes with a few unique considerations." },
    { type: "h3", text: "Venue Logistics" },
    { type: "p", text: "Venues like the Cochrane RancheHouse or Mitford Gardens may require coordination depending on layout and access. Photo booths are typically set up ahead of your event, but timing can be adjusted based on your preferences. Setup can also happen during the event if needed." },
    { type: "h3", text: "Outdoor Considerations" },
    { type: "p", text: "Cochrane weather can shift quickly, especially with chinook winds. Planning for stability and coverage helps keep everything running smoothly." },
    { type: "h3", text: "Space Requirements" },
    { type: "p", text: "Most booths are compact. Pole booth: about 6x6 ft. Larger setups: around 8x8 ft." },
    { type: "h3", text: "Booking Timeline" },
    { type: "p", text: "Peak times, especially around festivals and summer events, fill up quickly. Booking about 4 weeks in advance is common. Around 55% of Cochrane events combine indoor and outdoor elements, so flexibility matters when planning." },
    { type: "h2", text: "What Makes Photobooth Experience Different in Cochrane" },
    { type: "p", text: "Cochrane events have a specific feel. The service needs to match that." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events need different setups. Having multiple options means you're not forced into one style." },
    { type: "h3", text: "Built for Foothills and Community Events" },
    { type: "p", text: "Events here are more personal. Everything is designed to feel easy and natural so guests actually use the booth." },
    { type: "h3", text: "Full Coverage Across Cochrane" },
    { type: "p", text: "We service all areas, from central Cochrane to surrounding foothills and nearby locations." },
    { type: "h3", text: "Easy Photo and Video Access" },
    { type: "p", text: "Guests can access their content after the event without any extra steps. Simple and straightforward." },
  ],
  faqs: [
    { q: "Why choose a 360 photo booth for Cochrane festivals?", a: "It captures slow-motion video that works well for large, energetic events like the Highland Games, where guests want something fun to share." },
    { q: "How does a mirror photo booth work at Cochrane events?", a: "Guests stand in front of the mirror and take photos naturally. It feels simple and works for both casual and formal settings." },
    { q: "Can photo booths be used at outdoor Cochrane venues?", a: "Yes. Setups can be adjusted for outdoor locations, including parks and ranch-style venues." },
    { q: "What are the benefits of an audio guest book for Cochrane events?", a: "It captures voice messages from guests, creating something more personal than photos alone." },
    { q: "Can backdrops be customized for Cochrane corporate events?", a: "Yes. Backdrops can be designed to match branding, colors, and event themes." },
    { q: "How much space is needed for a pole photo booth in Cochrane?", a: "About 6x6 ft is enough, making it ideal for smaller venues or tighter layouts." },
    { q: "Are photo booths suitable for large Cochrane festivals?", a: "Yes. High-capacity setups can handle thousands of interactions across large events." },
    { q: "What events work best with a premium photo booth in Cochrane?", a: "Weddings, corporate events, and milestone celebrations benefit the most from higher-quality images and flexible setups." },
    { q: "How is setup handled for Cochrane photo booth rentals?", a: "Setup is coordinated based on your venue and event schedule. It's usually done ahead of time but can be adjusted if needed." },
    { q: "Can the same booth be used for different Cochrane event types?", a: "Yes. Booths can be customized with different overlays, templates, and backdrops to match the event." },
  ],
  image: "/locations/Cochrane.jpg",
  ctaSubtext: "If you're planning an event in Cochrane and want something that keeps people engaged, photo booth rentals are one of the simplest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
