<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:sitemapindex="http://www.sitemaps.org/schemas/sitemap/0.9"
  exclude-result-prefixes="sitemap sitemapindex">

  <xsl:output method="html" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>XML Sitemap — Photo Booth Experience</title>
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #f9f9f9; color: #333; }
          header { background: #141414; color: #fff; padding: 24px 40px; display: flex; align-items: center; gap: 16px; }
          header img { height: 36px; }
          header h1 { font-size: 18px; font-weight: 600; letter-spacing: 0.02em; }
          header p { font-size: 13px; color: #aaa; margin-top: 2px; }
          .container { max-width: 960px; margin: 40px auto; padding: 0 24px; }
          table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,0.08); }
          thead tr { background: #f0f0f0; }
          th { text-align: left; padding: 12px 20px; font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em; color: #666; }
          td { padding: 12px 20px; font-size: 14px; border-top: 1px solid #f0f0f0; }
          td a { color: #1a73e8; text-decoration: none; word-break: break-all; }
          td a:hover { text-decoration: underline; }
          tr:hover td { background: #fafafa; }
          .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; background: #e8f0fe; color: #1a73e8; }
          footer { text-align: center; padding: 32px; font-size: 12px; color: #aaa; }
        </style>
      </head>
      <body>
        <header>
          <div>
            <h1>Photo Booth Experience</h1>
            <p>XML Sitemap</p>
          </div>
        </header>
        <div class="container">
          <xsl:apply-templates/>
        </div>
        <footer>Generated by photoboothexperience.ca</footer>
      </body>
    </html>
  </xsl:template>

  <!-- Sitemap Index -->
  <xsl:template match="sitemapindex:sitemapindex">
    <p style="margin-bottom:16px;font-size:14px;color:#555;">
      This sitemap index contains <strong><xsl:value-of select="count(sitemapindex:sitemap)"/></strong> sitemaps.
    </p>
    <table>
      <thead>
        <tr>
          <th>Sitemap URL</th>
          <th>Last Modified</th>
        </tr>
      </thead>
      <tbody>
        <xsl:for-each select="sitemapindex:sitemap">
          <tr>
            <td><a href="{sitemapindex:loc}"><xsl:value-of select="sitemapindex:loc"/></a></td>
            <td><xsl:value-of select="sitemapindex:lastmod"/></td>
          </tr>
        </xsl:for-each>
      </tbody>
    </table>
  </xsl:template>

  <!-- URL Set -->
  <xsl:template match="sitemap:urlset">
    <p style="margin-bottom:16px;font-size:14px;color:#555;">
      This sitemap contains <strong><xsl:value-of select="count(sitemap:url)"/></strong> URLs.
    </p>
    <table>
      <thead>
        <tr>
          <th>URL</th>
          <th>Last Modified</th>
          <th>Change Freq</th>
          <th>Priority</th>
        </tr>
      </thead>
      <tbody>
        <xsl:for-each select="sitemap:url">
          <tr>
            <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
            <td><xsl:value-of select="sitemap:lastmod"/></td>
            <td><xsl:value-of select="sitemap:changefreq"/></td>
            <td>
              <xsl:if test="sitemap:priority">
                <span class="badge"><xsl:value-of select="sitemap:priority"/></span>
              </xsl:if>
            </td>
          </tr>
        </xsl:for-each>
      </tbody>
    </table>
  </xsl:template>

</xsl:stylesheet>
