"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Drumheller",
  heroSubtitle: "Drumheller photo booth rentals for weddings, reunions, and badlands events. Dust-ready setups, multiple booth options, and seamless service.",
  introParagraphs: [
    "Drumheller photo booth rentals bring something different to events set in one of the most unique landscapes in Alberta.",
    "The badlands don't look like anywhere else. Hoodoos, canyon views, open skies. Events here already feel distinct before anything else is added.",
    "But what makes those events memorable isn't just the location. It's what people do while they're there.",
    "That's where a photo booth fits in.",
    "It gives guests something interactive that works naturally in the environment. No staging. No pressure. Just quick moments captured as they happen, whether it's during a wedding, a reunion, or a festival.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Community festivals",
    "Corporate picnics",
    "Backyard gatherings and family reunions",
  ],
  introClosure: "You can choose from pole booths, 360 booths, mirror booths, premium setups, audio guest books, and custom badlands-themed backdrops. Everything is delivered and set up based on your event, with support to handle both indoor and outdoor conditions. Drumheller's environment comes with extremes. Temperatures can range from -35°C in winter to +35°C in summer, and dry air combined with dust and wind needs to be considered when planning any event.",
  contentBlocks: [
    { type: "h2", text: "Transform Drumheller Gatherings with Badlands Booths" },
    { type: "p", text: "Events in Drumheller aren't typical. They often involve outdoor venues, gravel surfaces, wind exposure, and dry dusty conditions. A photo booth needs to work within all of that." },
    { type: "h3", text: "Built for Dust and Wind" },
    { type: "p", text: "The badlands environment is dry. Fine dust can settle quickly, and wind speeds can exceed 30 km/h during open-air events. That means booth setups need to be stable and protected. Sealed equipment and weighted placement help keep everything running without interruption." },
    { type: "h3", text: "Keeps Guests Engaged in Open Environments" },
    { type: "p", text: "Outdoor events often spread people out. Guests move between areas, step away, or gather in smaller groups. A photo booth gives them a central point to come back to. It keeps interaction going without forcing it." },
    { type: "h3", text: "Creates Unique, Shareable Content" },
    { type: "p", text: "Photos taken in Drumheller don't just capture people. They capture the setting. Hoodoos, canyon views, and wide-open landscapes create a backdrop that makes every photo stand out." },
    { type: "h2", text: "Your Drumheller Booth Collection" },
    { type: "p", text: "Every event in Drumheller is different. The booth should match the environment." },
    { type: "h3", text: "Portable Pole Photo Booth in Drumheller" },
    { type: "p", text: "The pole booth is compact and easy to place. It works well for outdoor tents, smaller venues, birthday events, and corporate picnics. It's a strong choice for locations like the Royal Tyrrell Museum parking areas or smaller gathering spaces. Its small footprint helps keep setups simple." },
    { type: "h3", text: "Drumheller 360 Photo Booth" },
    { type: "p", text: "The 360 booth adds movement and energy. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It works well for weddings, festivals, amphitheatre events, and group gatherings. Placed near main gathering areas, it becomes a natural part of the event. Locations like the Drumheller Valley Outdoor Amphitheatre are ideal for this type of setup." },
    { type: "h3", text: "Drumheller Mirror Photo Booth" },
    { type: "p", text: "The mirror booth offers a more polished option. Guests stand in front of the mirror and take photos naturally. It fits well for weddings, family events, indoor gatherings, and museum or visitor centre events. It's simple to use and doesn't require explanation." },
    { type: "h3", text: "Drumheller Premium Photo Booth" },
    { type: "p", text: "The premium booth is built for larger events. It allows group photos, consistent lighting, and high-quality images. This works well for weddings, community events, corporate gatherings, and larger outdoor setups. It handles higher guest volume without slowing things down." },
    { type: "h3", text: "Drumheller Audio Guest Book" },
    { type: "p", text: "Photos show what the event looked like. Audio captures what people said. The audio guest book allows guests to leave voice messages using a phone-style setup. It's a strong addition for weddings, reunions, and family events. Placed near seating or gathering areas, it becomes a quieter, more personal part of the event." },
    { type: "h3", text: "Drumheller Premium Backdrops" },
    { type: "p", text: "Backdrops help tie everything together visually. In Drumheller, they often reflect the landscape. Options can include hoodoo silhouettes, canyon-inspired tones, and neutral designs that match outdoor settings. They help create consistency across all photos." },
    { type: "h2", text: "Perfect Drumheller Events for Photo Booth Rentals" },
    { type: "p", text: "Photo booths work across all types of events in Drumheller." },
    { type: "h3", text: "Drumheller Wedding Photo Booth" },
    { type: "p", text: "Weddings in Drumheller often take place in outdoor settings or unique locations like the Royal Tyrrell Museum grounds. A photo booth captures moments throughout the entire event, especially during transitions between ceremony and reception." },
    { type: "h3", text: "Corporate Picnics and Group Events" },
    { type: "p", text: "Corporate gatherings in Drumheller often happen in open spaces like Horseshoe Canyon or Midland Provincial Park. Photo booths provide a structured activity without interrupting the flow of the event." },
    { type: "h3", text: "Community Festivals and Events" },
    { type: "p", text: "Events like Drumheller Days bring the community together each year. Locations around the World's Largest Dinosaur and surrounding areas see steady traffic during these events. Photo booths designed for volume work best in these environments." },
    { type: "h3", text: "Family Reunions in Drumheller" },
    { type: "p", text: "Family gatherings often take place at picnic areas or outdoor locations. Photo booths help capture group moments without requiring formal setup." },
    { type: "h3", text: "Backyard Events and Private Homes" },
    { type: "p", text: "Neighborhoods around Drumheller often host smaller gatherings. Portable booth setups make it easy to bring the same experience into a more casual environment." },
    { type: "h2", text: "Drumheller Venue-Specific Planning Guide" },
    { type: "p", text: "Planning in Drumheller requires attention to the environment." },
    { type: "h3", text: "Royal Tyrrell Museum" },
    { type: "p", text: "The Dinosaur Hall parking area requires stable placement on gravel and may need base support for equipment. It includes access to generator power areas. Shuttle coordination may be required depending on the event setup." },
    { type: "h3", text: "World's Largest Dinosaur" },
    { type: "p", text: "This location offers a large parking area for setup, nearby visitor centre facilities, and high foot traffic during peak times. Positioning near central areas helps maximize usage." },
    { type: "h3", text: "Horseshoe Canyon" },
    { type: "p", text: "Outdoor setups here include picnic tables and open space, no direct power access, and wind and dust exposure. Generator use and stable placement are important." },
    { type: "h3", text: "Positioning Tip" },
    { type: "p", text: "Placing the booth near high-traffic areas like shuttle drop-offs or central gathering points helps maintain consistent usage." },
    { type: "h2", text: "Why Drumheller Locals Choose Photobooth Experience" },
    { type: "p", text: "Events in Drumheller require a different approach. The environment matters." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events need different setups. Having multiple booth types allows you to choose what fits best." },
    { type: "h3", text: "Built for Badlands Conditions" },
    { type: "p", text: "Dust, wind, and temperature swings are part of the environment. Setups are designed to handle those conditions." },
    { type: "h3", text: "Local Coverage Across Drumheller" },
    { type: "p", text: "From central locations to surrounding areas, coverage is consistent across the region." },
    { type: "h3", text: "Simple Photo and Video Access" },
    { type: "p", text: "Guests can access their content after the event without extra steps." },
  ],
  faqs: [
    { q: "Is a 360 photo booth a good fit for Royal Tyrrell Museum events?", a: "Yes. It captures movement and energy in open environments, making it ideal for outdoor wedding or event setups." },
    { q: "How does a mirror photo booth work at Drumheller events?", a: "Guests stand in front of the mirror and take photos naturally. It's simple and works for both indoor and outdoor environments." },
    { q: "Can photo booths handle dust and wind in Drumheller?", a: "Yes. Setups are planned with sealed equipment and stable placement to handle badlands conditions." },
    { q: "Why add an audio guest book to a Drumheller event?", a: "It captures voice messages from guests, creating something more personal than photos alone." },
    { q: "Can backdrops match Drumheller landscapes?", a: "Yes. Backdrops can reflect canyon tones and natural surroundings while keeping photos consistent." },
  ],
  image: "/locations/Drumheller.jpg",
  ctaSubtext: "If you're planning an event in Drumheller and want something that keeps people engaged while fitting the environment, photo booth rentals are one of the easiest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
