"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Didsbury",
  heroSubtitle: "Didsbury photo booth rentals for weddings, grad ceremonies, and events. Reliable setups, multiple booth options, and seamless service.",
  introParagraphs: [
    "Didsbury photo booth rentals bring something interactive to events that are built around community, family, and rural traditions.",
    "In Didsbury, events feel personal. Whether it's a wedding at Bergthal Event Centre, a gathering at the Didsbury Memorial Complex, or a small celebration at the historic train station, people show up to be part of the experience.",
    "That's where a photo booth fits in.",
    "It gives guests something to step into right away. No pressure, no waiting, just quick moments captured naturally as the event unfolds.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Agricultural shows",
    "Grad ceremonies",
    "Family reunions",
    "Corporate dinners",
  ],
  introClosure: "You can choose from pole booths, 360 booths, mirror booths, premium setups, audio guest books, and prairie-inspired backdrops. Everything is delivered and set up based on your event, with support so everything runs smoothly. Didsbury's seasonal shifts play a big role in event planning. The first frost typically arrives around mid-September, which often moves events indoors earlier than expected.",
  contentBlocks: [
    { type: "h2", text: "Perfect for Didsbury's Indoor and Outdoor Events" },
    { type: "p", text: "Events in Didsbury often shift between outdoor and indoor settings depending on the time of year. A photo booth needs to work in both." },
    { type: "h3", text: "Keeps Guests Engaged Throughout the Event" },
    { type: "p", text: "Even smaller events have slower moments. Guests move between spaces, talk, or step away. A photo booth gives them something to return to. It keeps the event active without needing structure." },
    { type: "h3", text: "Built for Seasonal Changes" },
    { type: "p", text: "Didsbury events are affected by early fall frost, changing temperatures, and chinook winds reaching 40 km/h or more. Photo booths need to be stable and adaptable across these conditions." },
    { type: "h3", text: "Fits Local Event Styles" },
    { type: "p", text: "Most events in Didsbury happen in community halls, rural venues, historic spaces, and outdoor ceremony areas. Photo booths adapt easily to these environments." },
    { type: "h2", text: "Your Didsbury Booth Collection" },
    { type: "p", text: "Each booth option works differently depending on your event." },
    { type: "h3", text: "Space-Saving Pole Photo Booth in Didsbury" },
    { type: "p", text: "The pole booth is compact and easy to place. It works well for smaller venues, community halls, grad ceremonies, and indoor gatherings. It fits easily into spaces like the Didsbury Memorial Complex Multi-Purpose Room." },
    { type: "h3", text: "Didsbury 360 Photo Booth" },
    { type: "p", text: "The 360 booth adds movement and energy. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It's a strong choice for weddings, community events, barn dances, and larger gatherings. It works especially well at venues like Bergthal Event Centre where there's room for group interaction." },
    { type: "h3", text: "Didsbury Mirror Photo Booth" },
    { type: "p", text: "The mirror booth offers a more refined experience. Guests stand in front of the mirror and take photos naturally. It fits well for weddings, showers, indoor receptions, and smaller venues. It works particularly well in spaces like the Didsbury Train Station where layout is more compact." },
    { type: "h3", text: "Didsbury Premium Photo Booth" },
    { type: "p", text: "The premium booth focuses on quality and flexibility. It allows larger group photos, consistent lighting, and high-quality images. This is a strong option for weddings, community events, and larger receptions. It works well in venues like Bergthal Event Centre, which can host up to around 150 guests." },
    { type: "h3", text: "Didsbury Audio Guest Book" },
    { type: "p", text: "Photos show what happened. Audio captures what people said. The audio guest book allows guests to leave voice messages during your event using a phone-style setup. It's a great addition for weddings, family gatherings, and community events. It gives you something to revisit after the event." },
    { type: "h3", text: "Didsbury Premium Backdrops" },
    { type: "p", text: "Backdrops help define how your photos look. In Didsbury, they often reflect prairie landscapes, canola fields, and rural themes. They help create consistency across all photos." },
    { type: "h2", text: "Perfect Didsbury Events for Photo Booth Rentals" },
    { type: "p", text: "Photo booths work across all types of events in Didsbury." },
    { type: "h3", text: "Didsbury Wedding Photo Booth" },
    { type: "p", text: "Weddings in Didsbury often take place at venues like Bergthal Event Centre or community halls. A photo booth captures moments throughout the event, from ceremony to reception." },
    { type: "h3", text: "Community Events at Didsbury Memorial Complex" },
    { type: "p", text: "The Multi-Purpose Room is a common location for local events. Its layout allows for easy placement and steady guest flow." },
    { type: "h3", text: "Agricultural Shows and Local Events" },
    { type: "p", text: "Didsbury has a strong agricultural community. Events at the Agricultural Society grounds bring in groups that benefit from interactive elements like photo booths." },
    { type: "h3", text: "Train Station Events" },
    { type: "p", text: "The historic Didsbury Train Station is often used for smaller gatherings. It works well with compact booth setups that don't take up too much space." },
    { type: "h3", text: "Family Reunions and Gatherings" },
    { type: "p", text: "Community halls and rural venues are often used for reunions. Photo booths give families a way to capture group moments easily." },
    { type: "h2", text: "Didsbury Venue-Specific Planning Guide" },
    { type: "p", text: "Planning in Didsbury requires attention to layout and timing." },
    { type: "h3", text: "Bergthal Event Centre" },
    { type: "p", text: "This venue includes an indoor hall, kitchen access, and outdoor ceremony space. Because it's located outside of town, shuttle coordination may be needed for guests. Peak wedding dates are often booked more than 12 months in advance." },
    { type: "h3", text: "Didsbury Memorial Complex" },
    { type: "p", text: "The Multi-Purpose Room offers indoor event space, kitchen access, and proximity to the Aquatic Centre and arena. Guest flow often moves naturally from entry areas into the event space." },
    { type: "h3", text: "Didsbury Train Station" },
    { type: "p", text: "This venue is ideal for smaller gatherings, 50 to 75 guest events, and intimate weddings. Its compact layout pairs well with smaller booth setups." },
    { type: "h3", text: "Seasonal Considerations" },
    { type: "p", text: "Didsbury's event planning changes quickly after mid-September. Outdoor events decrease, indoor venues become the focus, and chinook winds can impact outdoor setups. Planning for indoor options is common after early fall." },
    { type: "h2", text: "Why Didsbury Locals Choose Photobooth Experience" },
    { type: "p", text: "Events in Didsbury require flexibility. The service needs to match the environment." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events need different setups. Having multiple booth types allows you to choose what fits best." },
    { type: "h3", text: "Built for Rural and Community Events" },
    { type: "p", text: "Didsbury events are personal and local. Everything is designed to feel simple and natural for guests." },
    { type: "h3", text: "Full Coverage Across Didsbury" },
    { type: "p", text: "We service the entire area, including surrounding rural locations." },
    { type: "h3", text: "Easy Access to Photos and Videos" },
    { type: "p", text: "Guests can access their content after the event without extra steps." },
  ],
  faqs: [
    { q: "Is a 360 photo booth a good fit for Bergthal Event Centre weddings?", a: "Yes. It captures movement and group interaction, making it ideal for larger wedding receptions." },
    { q: "How does a mirror photo booth work at Didsbury events?", a: "Guests stand in front of the mirror and take photos naturally. It works well in both small and large venues." },
    { q: "Can photo booths handle outdoor Didsbury events?", a: "Yes. Setups can be adjusted for outdoor conditions, including wind and temperature changes." },
    { q: "Why add an audio guest book to a Didsbury event?", a: "It captures voice messages from guests, creating something more personal than photos." },
    { q: "Can backdrops match Didsbury rural themes?", a: "Yes. Backdrops can reflect prairie landscapes and event-specific styles." },
  ],
  image: "/locations/Didsbury.jpg",
  ctaSubtext: "If you're planning an event in Didsbury and want something that keeps people engaged, photo booth rentals are one of the easiest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
