"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Claresholm",
  heroSubtitle: "Claresholm photo booth rentals for weddings, stampedes, and events. Prairie-ready setups, multiple booth options, and seamless service.",
  introParagraphs: [
    "Claresholm photo booth rental services are built for events that feel real, local, and connected to the community.",
    "In Claresholm, events are personal. Whether it's a wedding at the community hall, a summer stampede gathering, or a backyard reunion on a ranch property, people show up to be part of it.",
    "That's where a photo booth fits in.",
    "It gives guests something to step into right away. No pressure, no complicated setup, just genuine moments captured as they happen.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Festivals and agricultural events",
    "Corporate gatherings",
    "Backyard family events",
    "Reunions",
  ],
  introClosure: "You can choose from pole booths, 360 booths, mirror booths, premium setups, audio guest books, and custom prairie and ranch-inspired backdrops. Everything is delivered and set up based on your event, with support to keep everything running smoothly in both indoor and outdoor settings. Claresholm is a southern Alberta town of around 3,800 residents along Highway 2, with strong roots in ranching and agriculture that shape how events are hosted and experienced.",
  contentBlocks: [
    { type: "h2", text: "Advantages of Photo Booths for Claresholm Events" },
    { type: "p", text: "Events in Claresholm are built around people, not production. That's why interactive elements matter more." },
    { type: "h3", text: "Keeps Guests Engaged at Local Gatherings" },
    { type: "p", text: "At smaller, community-based events, you need something that gets people involved quickly. A photo booth does that naturally. Guests step in, take photos, and bring others along." },
    { type: "h3", text: "Built for Prairie and Chinook Weather" },
    { type: "p", text: "Claresholm weather can shift quickly. You're dealing with chinook winds, sudden temperature swings, and dry prairie conditions. Photo booth setups need to be stable and adaptable to handle these changes. Chinooks can bring temperature swings of up to 20°C in a short period, which impacts how outdoor events are planned." },
    { type: "h3", text: "Works in Indoor and Outdoor Spaces" },
    { type: "p", text: "Events in Claresholm often take place in community halls, legion halls, agricultural grounds, and rural ranch properties. Photo booths can adapt to all of these environments." },
    { type: "h3", text: "Creates Shareable Content in Rural Settings" },
    { type: "p", text: "Even in smaller towns, guests want to share their experience. Digital galleries make it easy for guests to access and post photos from anywhere." },
    { type: "h2", text: "Matching Photo Booths to Claresholm Celebrations" },
    { type: "p", text: "Each booth option works differently depending on the event." },
    { type: "h3", text: "Pole Photo Booth for Backyard Use in Claresholm" },
    { type: "p", text: "The pole booth is compact and portable. It works well for backyard reunions, ranch weddings, and family gatherings. It's easy to transport and set up on rural properties." },
    { type: "h3", text: "360 Photo Booth Claresholm" },
    { type: "p", text: "The 360 booth adds movement and energy. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It's a strong fit for stampede events, festivals, birthday parties, and large gatherings. It works especially well at events held at the Claresholm Ag Society Grounds." },
    { type: "h3", text: "Mirror Photo Booth Claresholm" },
    { type: "p", text: "The mirror booth offers a more refined experience. Guests stand in front of the mirror and take photos naturally. It works well for weddings, indoor receptions, corporate events, and showers. It's simple to use and fits well in formal venues." },
    { type: "h3", text: "Enhanced Options: Backdrops & Audio Guest Books" },
    { type: "p", text: "Premium features add more depth to the experience. Backdrops can reflect ranch and prairie themes, agricultural heritage, and neutral tones for formal events. Audio guest books allow guests to leave voice messages, making them ideal for weddings, baby showers, and milestone events." },
    { type: "h2", text: "Recommended Claresholm Venues for Photo Booth Setups" },
    { type: "p", text: "Photo booths can be set up almost anywhere in Claresholm. Here's how they fit into local venues." },
    { type: "h3", text: "Community Halls" },
    { type: "p", text: "The Claresholm Community Hall is best for weddings, corporate events, and showers. Large indoor space with a flexible layout allows easy flow from dining to photos." },
    { type: "h3", text: "Agricultural Grounds" },
    { type: "p", text: "The Claresholm Ag Society Grounds is best for festivals, stampede events, and fairs. Indoor and outdoor flexibility with high traffic areas make it ideal." },
    { type: "h3", text: "Legion Facilities" },
    { type: "p", text: "The Claresholm Legion is best for birthdays, corporate gatherings, and community events. It provides a reliable indoor environment with consistent guest movement." },
    { type: "h3", text: "Rural Ranch Properties" },
    { type: "p", text: "Acreages along Old Highway 2 are best for backyard weddings, family reunions, and private events. Open space placement adaptable for outdoor conditions makes ranch setups work." },
    { type: "h3", text: "Arena and Banquet Spaces" },
    { type: "p", text: "Local Elks Lodge and similar spaces are best for banquets, large gatherings, and community events. Open layout with high capacity allows for flexible setup." },
    { type: "h2", text: "Claresholm Event Planning with Photo Booths" },
    { type: "p", text: "Planning in Claresholm requires flexibility and awareness of local conditions." },
    { type: "h3", text: "Match Booth Type to Event Style" },
    { type: "p", text: "360 booths work best for high-energy outdoor events. Mirror booths suit formal indoor receptions. Pole booths fit backyard and rural setups." },
    { type: "h3", text: "Plan for Weather Changes" },
    { type: "p", text: "Chinook conditions can shift quickly. Indoor backup options are often used for outdoor events." },
    { type: "h3", text: "Use Local-Themed Backdrops" },
    { type: "p", text: "Prairie and ranch-inspired designs help photos feel more connected to the event." },
    { type: "h3", text: "Book Early for Stampede Season" },
    { type: "p", text: "Peak times include summer fairs, stampede events, and wedding season. Booking ahead helps secure availability." },
    { type: "h2", text: "Why Claresholm Locals Choose Photobooth Experience" },
    { type: "p", text: "Events in Claresholm require a practical approach." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events need different setups. Having multiple booth types allows you to choose what fits best." },
    { type: "h3", text: "Built for Prairie Conditions" },
    { type: "p", text: "Wind, dust, and temperature swings are part of the environment. Setups are designed to handle those conditions." },
    { type: "h3", text: "Full Coverage Across Claresholm" },
    { type: "p", text: "We service all areas, including rural ranch properties and town venues." },
    { type: "h3", text: "Easy Access to Photos and Videos" },
    { type: "p", text: "Guests can access their content after the event without extra steps." },
  ],
  faqs: [
    { q: "Claresholm wedding photo booth rental options?", a: "Mirror booths are a strong choice for indoor receptions, offering interactive guest experiences and clean photo output." },
    { q: "360 photo booth rental Claresholm for festivals?", a: "Yes. 360 booths work well for dynamic video capture at Ag Society events and stampede gatherings." },
    { q: "Photo booth for baby showers in Claresholm?", a: "Yes. Audio guest books capture personal messages, making them a popular option for showers." },
    { q: "Backyard photo booth rental Claresholm suitable?", a: "Pole booths are portable and ideal for ranch properties and acreage setups." },
    { q: "Corporate photo booth Claresholm options?", a: "Premium setups with custom backdrops work well for Legion halls and community events." },
    { q: "Mirror photo booth rental Claresholm for birthdays?", a: "Yes. Mirror booths provide interactive experiences for both kids and adults." },
    { q: "Does Claresholm photo booth rental handle outdoor events?", a: "Yes. Booths are designed to handle prairie wind and outdoor conditions." },
    { q: "Gender reveal photo booth ideas in Claresholm?", a: "360 booths paired with themed backdrops create engaging reveal moments." },
    { q: "Photo booth for family reunions Claresholm?", a: "Portable setups fit large acreages and multi-family gatherings." },
    { q: "What makes Claresholm photo booths stand out?", a: "Ranch-inspired backdrops and local themes create a unique, community-focused experience." },
  ],
  image: "/locations/Claresholm.jpg",
  ctaSubtext: "If you're planning an event in Claresholm and want something that keeps people engaged, photo booth rentals are one of the easiest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
