"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Turner Valley",
  heroSubtitle: "Turner Valley photo booth rentals for weddings, grads, and events. Wind-ready setups, multiple booth options, and seamless service.",
  introParagraphs: [
    "Turner Valley photo booth rental services are built for events that sit right between prairie and mountain landscapes.",
    "In Turner Valley, events feel grounded. Weddings, grad ceremonies, oilfield gatherings, and community events all carry that same local energy. People show up to be part of it, not just attend.",
    "That's where a photo booth fits in.",
    "It gives guests something to step into right away. No structure needed. Just quick moments captured naturally as the event unfolds.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Oilfield corporate events",
    "Community fairs",
    "Grad ceremonies",
    "Family reunions",
  ],
  introClosure: "You can choose from pole booths, 360 booths, mirror booths, premium setups, audio guest books, and prairie-inspired backdrops. Everything is delivered and set up based on your event, with support to keep everything running smoothly. Turner Valley weather is a major factor in event planning. Chinook winds in the area can exceed 50 km/h, especially in open foothill and ranch locations, which means outdoor setups need proper anchoring and stability.",
  contentBlocks: [
    { type: "h2", text: "Built for Turner Valley's Ranch-to-Community Events" },
    { type: "p", text: "Events in Turner Valley often move between environments. You'll see indoor halls, gymnasium spaces, rural ranch properties, and outdoor ceremony areas. A photo booth needs to work across all of them." },
    { type: "h3", text: "Keeps Guests Engaged Naturally" },
    { type: "p", text: "Events here don't rely on rigid schedules. Guests move around, talk, and take part in different parts of the event. A photo booth gives them something to return to. It keeps the energy consistent without forcing interaction." },
    { type: "h3", text: "Handles Foothills Weather Conditions" },
    { type: "p", text: "Turner Valley events deal with chinook winds over 50 km/h, summer hail storms, early fall frost, and rapid temperature changes. Photo booth setups need to be stable and adaptable to handle these conditions without interruption." },
    { type: "h3", text: "Fits Local Event Spaces" },
    { type: "p", text: "Most events in Turner Valley take place in legion halls, community centres, high school gyms, rural banquet halls, and ranch venues. Photo booths adapt easily to these environments." },
    { type: "h2", text: "Your Turner Valley Booth Collection" },
    { type: "p", text: "Each booth option fits different types of events." },
    { type: "h3", text: "Compact Pole Photo Booth in Turner Valley" },
    { type: "p", text: "The pole booth is compact and easy to place. It works well for smaller venues, community halls, grad ceremonies, and corporate gatherings. It fits easily into spaces like the Turner Valley Legion Hall or gym staging areas at Oilfields High School." },
    { type: "h3", text: "Turner Valley 360 Photo Booth" },
    { type: "p", text: "The 360 booth adds movement and energy. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It's a strong fit for weddings, ranch events, community gatherings, and larger receptions. It works well in open layouts where guests can move freely." },
    { type: "h3", text: "Turner Valley Mirror Photo Booth" },
    { type: "p", text: "The mirror booth offers a more refined experience. Guests stand in front of the mirror and take photos naturally. It fits well for weddings, showers, indoor receptions, and smaller venues. It works especially well in spaces like the Turner Valley Community Centre." },
    { type: "h3", text: "Turner Valley Premium Photo Booth" },
    { type: "p", text: "The premium booth focuses on quality and flexibility. It allows larger group photos, consistent lighting, and high-quality images. This is ideal for weddings, grad ceremonies, corporate events, and larger gatherings. It works well in gymnasium setups like Oilfields High School where larger groups are common." },
    { type: "h3", text: "Turner Valley Audio Guest Book" },
    { type: "p", text: "Photos show what happened. Audio captures what people said. The audio guest book allows guests to leave voice messages using a phone-style setup. It's a strong addition for weddings, family gatherings, and corporate events. It creates something meaningful you can revisit after the event." },
    { type: "h3", text: "Turner Valley Premium Backdrops" },
    { type: "p", text: "Backdrops help define the look of your photos. In Turner Valley, they often reflect prairie sunsets, canola fields, and rural landscapes. They help create a consistent visual style." },
    { type: "h2", text: "Perfect Turner Valley Events for Photo Booth Rentals" },
    { type: "p", text: "Photo booths work across all types of events in Turner Valley." },
    { type: "h3", text: "Turner Valley Wedding Photo Booth" },
    { type: "p", text: "Weddings in Turner Valley often take place at the Turner Valley Legion Hall, rural foothill ranches, or community venues. A photo booth captures moments throughout the entire event, from ceremony to reception." },
    { type: "h3", text: "Grad Ceremonies at Oilfields High School" },
    { type: "p", text: "Grad events often take place in gymnasium spaces. Bleacher seating naturally creates flow toward central areas, making photo booth placement simple and effective." },
    { type: "h3", text: "Oilfield Corporate Events" },
    { type: "p", text: "Turner Valley has strong ties to oilfield work. Corporate events and safety meetings benefit from having something interactive for guests." },
    { type: "h3", text: "Community Fairs and Events" },
    { type: "p", text: "Local fairs and community gatherings bring people together throughout the year. Photo booths add something interactive without disrupting the flow." },
    { type: "h3", text: "Family Reunions and Gatherings" },
    { type: "p", text: "Rural venues and community halls are common for reunions. Photo booths provide a simple way to capture group moments." },
    { type: "h3", text: "Restaurant and Banquet Events" },
    { type: "p", text: "Some events take place in local restaurants with banquet space. Photo booths can be set up where space allows." },
    { type: "h2", text: "Turner Valley Venue-Specific Planning Guide" },
    { type: "p", text: "Planning in Turner Valley requires attention to layout and logistics." },
    { type: "h3", text: "Turner Valley Legion Hall" },
    { type: "p", text: "This venue includes a rectangular layout, kitchen access, and open reception space. It supports flexible booth placement and steady guest flow." },
    { type: "h3", text: "Oilfields High School" },
    { type: "p", text: "The gymnasium offers large capacity for events, direct access from parking, and an open layout for flexible setups. Bleacher seating creates natural movement toward central areas." },
    { type: "h3", text: "Turner Valley Community Centre" },
    { type: "p", text: "This space includes a multi-purpose room, indoor power access, and proximity to outdoor areas. It works well for family and community events." },
    { type: "h3", text: "Rural Foothills Ranches" },
    { type: "p", text: "Many weddings take place on private land outside of town. These venues often require stable setup on gravel, additional anchoring for wind, and planning for outdoor conditions. Chinook winds can exceed 50 km/h, so proper setup is important." },
    { type: "h2", text: "Why Turner Valley Locals Choose Photobooth Experience" },
    { type: "p", text: "Events in Turner Valley require flexibility. The service needs to match the environment." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events need different setups. Having multiple booth types allows you to choose what fits best." },
    { type: "h3", text: "Built for Foothills Conditions" },
    { type: "p", text: "Wind, weather, and terrain all play a role. Setups are designed to handle those conditions." },
    { type: "h3", text: "Full Coverage Across Turner Valley" },
    { type: "p", text: "We service the entire area, including surrounding foothill and rural locations." },
    { type: "h3", text: "Easy Access to Photos and Videos" },
    { type: "p", text: "Guests can access their content after the event without extra steps." },
  ],
  faqs: [
    { q: "Is a 360 photo booth a good fit for Turner Valley Legion weddings?", a: "Yes. It captures movement and group interaction in open reception spaces." },
    { q: "How does a mirror photo booth work at Turner Valley events?", a: "Guests stand in front of the mirror and take photos naturally. It works well in both small and large venues." },
    { q: "Can photo booths handle Turner Valley wind conditions?", a: "Yes. Setups are designed with stability in mind to handle foothill chinook winds." },
    { q: "Why add an audio guest book to a Turner Valley event?", a: "It captures voice messages from guests, creating something more personal than photos." },
    { q: "Can backdrops match Turner Valley rural themes?", a: "Yes. Backdrops can reflect prairie and foothill landscapes." },
  ],
  image: "/locations/Turner Valley.jpg",
  ctaSubtext: "If you're planning an event in Turner Valley and want something that keeps people engaged, photo booth rentals are one of the easiest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
