"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Three Hills",
  heroSubtitle: "Three Hills photo booth rentals for weddings, festivals, and events. Prairie-ready setups, multiple booth options, and seamless service.",
  introParagraphs: [
    "Three Hills photo booth rental services are built for events that feel local, personal, and community-driven.",
    "In Three Hills, events aren't about scale. They're about connection. Whether it's a wedding at a community hall, a family reunion on an acreage, or a summer event during Stampede season, people show up to be part of it.",
    "That's where a photo booth fits in.",
    "It gives guests something to step into right away. No pressure, no setup stress, just real moments captured naturally throughout the event.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Festivals and local events",
    "Corporate gatherings",
    "Backyard family events",
  ],
  introClosure: "You can choose from pole booths, 360 booths, mirror booths, premium setups, audio guest books, and custom prairie-inspired backdrops. Everything is delivered, set up based on your event, and supported so it runs smoothly anywhere, whether indoors or outdoors. Three Hills is a smaller prairie town with a population of around 3,200, and its agriculture-driven lifestyle means events are often family-focused and community-centered.",
  contentBlocks: [
    { type: "h2", text: "Why Rent a Photo Booth in Three Hills" },
    { type: "p", text: "Events in Three Hills are built around people, not production. That's exactly why photo booths work so well here." },
    { type: "h3", text: "Adds Interaction to Smaller Gatherings" },
    { type: "p", text: "At smaller events, you need something that gets people involved quickly. A photo booth does that without effort. Guests step in, take photos, and bring others along." },
    { type: "h3", text: "Works for Indoor and Outdoor Setups" },
    { type: "p", text: "Events in Three Hills often happen in community halls, school gyms, acreages, and fairgrounds. Photo booths can adapt to all of these environments without requiring complicated setup." },
    { type: "h3", text: "Handles Prairie Weather" },
    { type: "p", text: "Three Hills weather changes quickly. You're dealing with chinook winds, summer storms, and seasonal temperature shifts. Photo booth setups need to work in both indoor and outdoor conditions." },
    { type: "h3", text: "Easy Sharing for Guests" },
    { type: "p", text: "Guests don't just take photos. They share them. Even in rural areas, instant digital galleries make it easy for guests to access and post their content." },
    { type: "h2", text: "Best Photo Booth Types for Three Hills Events" },
    { type: "p", text: "Different events need different setups. Here's how each booth fits Three Hills events." },
    { type: "h3", text: "Pole Photo Booth for Backyard Gatherings" },
    { type: "p", text: "The pole booth is compact and portable. It works well for backyard reunions, acreage events, and small gatherings. It's easy to set up in open prairie spaces and doesn't take up much room." },
    { type: "h3", text: "360 Photo Booth in Three Hills" },
    { type: "p", text: "The 360 booth adds movement and energy. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It's a strong fit for festivals, school events, birthday parties, and large gatherings. It works especially well at events like the Three Hills Stampede where groups want something interactive." },
    { type: "h3", text: "Mirror Photo Booth Rental in Three Hills" },
    { type: "p", text: "The mirror booth offers a more polished experience. Guests stand in front of the mirror and take photos naturally. It works well for weddings, indoor receptions, corporate events, and showers. It's simple to use and fits well in indoor venues." },
    { type: "h3", text: "Premium Booths with Backdrops & Audio Guest Books" },
    { type: "p", text: "Premium setups allow larger group photos, consistent lighting, and clean high-quality images. Backdrops can reflect prairie landscapes, grain elevators, and sunset tones. Audio guest books add another layer by capturing voice messages during events like weddings and baby showers." },
    { type: "h2", text: "Top Three Hills Venues for Photo Booth Setups" },
    { type: "p", text: "Photo booths can be set up almost anywhere in Three Hills. Here's how they fit into common local venues." },
    { type: "h3", text: "Community Halls" },
    { type: "p", text: "The Three Hills Community Hall is best for weddings, reunions, and community events. Setups use indoor placement with flexible layouts and natural flow from dining to photos." },
    { type: "h3", text: "Schools" },
    { type: "p", text: "The Three Hills School of Music is best for grad ceremonies, corporate events, and performances. Large open spaces and bleacher seating create natural movement toward booths." },
    { type: "h3", text: "Agricultural Grounds" },
    { type: "p", text: "The Kneehill County Fairgrounds is best for festivals, Stampede events, and outdoor gatherings. Indoor and outdoor flexibility combined with high traffic areas allow for consistent usage." },
    { type: "h3", text: "Private Acreages" },
    { type: "p", text: "Rural properties off Highway 21 are best for backyard weddings, family reunions, and private celebrations. Open space placement and adaptable outdoor conditions make these setups work." },
    { type: "h3", text: "Restaurants & Banquet Rooms" },
    { type: "p", text: "These locations are best for community dinners, corporate events, and smaller gatherings. Coordinating with dining layout creates smooth flow from tables to the photo area." },
    { type: "h2", text: "Photo Booth Tips for Three Hills Weather & Events" },
    { type: "p", text: "Planning in Three Hills means thinking about conditions." },
    { type: "h3", text: "Wind and Outdoor Setup" },
    { type: "p", text: "Prairie wind can affect outdoor events. Pole and 360 booths can be positioned in more sheltered areas to maintain stability." },
    { type: "h3", text: "Indoor Backup for Seasonal Events" },
    { type: "p", text: "Early fall weather can shift quickly. Indoor options are often used as backup for outdoor ceremonies." },
    { type: "h3", text: "Backdrop Selection" },
    { type: "p", text: "Backdrops that reflect local scenery work best. Prairie sunsets and agricultural themes help photos feel more connected to the setting." },
    { type: "h3", text: "Event Timing" },
    { type: "p", text: "Peak times in Three Hills include summer festivals, Stampede season, and school graduations. Booking ahead is important during these periods." },
    { type: "h2", text: "Why Three Hills Locals Choose Photobooth Experience" },
    { type: "p", text: "Events in Three Hills need a simple, flexible approach." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events need different setups. Having options makes it easier to match the event." },
    { type: "h3", text: "Built for Rural Events" },
    { type: "p", text: "Three Hills events often take place outside traditional venues. Everything is designed to work in those environments." },
    { type: "h3", text: "Full Coverage Across Three Hills" },
    { type: "p", text: "We service all areas, including community halls, schools, acreages, and banquet rooms." },
    { type: "h3", text: "Easy Access to Photos and Videos" },
    { type: "p", text: "Guests can access their content after the event without extra steps." },
  ],
  faqs: [
    { q: "What's the best photo booth for Three Hills weddings?", a: "Mirror booths work well for indoor receptions, while premium setups handle larger guest groups." },
    { q: "Can we use a photo booth outdoors in Three Hills?", a: "Yes. Portable setups work well for prairie and acreage environments." },
    { q: "Is there a photo booth option for baby showers in Three Hills?", a: "Yes. Audio guest books add a personal element by capturing voice messages." },
    { q: "How early should we book for Three Hills festivals?", a: "Booking 3 to 6 months in advance is common for peak seasons like Stampede." },
    { q: "Do you offer corporate photo booths in Three Hills?", a: "Yes. Setups can be arranged for schools, community halls, and private venues." },
    { q: "What are good gender reveal photo booth ideas in Three Hills?", a: "360 booths with themed backdrops work well for capturing reactions." },
    { q: "Can we have a photo booth for a backyard reunion in Three Hills?", a: "Yes. Pole booths are portable and ideal for acreage setups." },
    { q: "What makes photo booths unique in Three Hills?", a: "Local-themed backdrops and community-focused events create a different experience." },
    { q: "How long does setup take for Three Hills events?", a: "Setup is coordinated based on your event schedule and location." },
    { q: "How do guests access photos after a Three Hills event?", a: "Guests receive access to a digital gallery for easy viewing and sharing." },
  ],
  image: "/locations/Three Hills.jpg",
  ctaSubtext: "If you're planning an event in Three Hills and want something that keeps people engaged, photo booth rentals are one of the easiest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
