"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Sundre",
  heroSubtitle: "Sundre photo booth rentals for weddings, rodeos, and mountain events. Weather-ready setups, multiple booth options, and seamless service.",
  introParagraphs: [
    "Sundre photo booth rental services are built for events that sit right at the edge of prairie and mountain landscapes.",
    "In Sundre, events feel different. You've got foothill views, ranch properties, and a steady flow of summer visitors. Whether it's a wedding near the river, a rodeo weekend event, or a backyard gathering on acreage, people show up ready to be part of the experience.",
    "That's where a photo booth fits in.",
    "It gives guests something to step into right away. No pressure, no waiting, just natural moments captured as they happen.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Rodeos and festivals",
    "Corporate retreats",
    "Backyard family gatherings",
    "Reunions",
  ],
  introClosure: "You can choose from pole booths, 360 booths, mirror booths, premium setups, audio guest books, and custom foothill-inspired backdrops. Everything is delivered and set up based on your event, with support so everything runs smoothly across both indoor and outdoor environments. Sundre has a population of around 2,700 residents and sits about 100 km north of Calgary. Its mix of tourism, forestry, and agriculture creates a strong outdoor event culture throughout the year.",
  contentBlocks: [
    { type: "h2", text: "Why Sundre Events Need Specialized Photo Booths" },
    { type: "p", text: "Events in Sundre aren't typical indoor setups. They're often outdoor, spread across large properties, weather-dependent, and multi-generational. A photo booth needs to handle all of that." },
    { type: "h3", text: "Built for Mountain and Foothill Weather" },
    { type: "p", text: "Sundre weather changes quickly. You're dealing with summer highs around 22°C, afternoon rain showers, wind and elevation shifts, and about 120 rainy days annually, which makes flexibility important when planning outdoor events. Photo booths need to be portable and adaptable to keep everything running smoothly." },
    { type: "h3", text: "Keeps Guests Engaged Across Large Spaces" },
    { type: "p", text: "At acreage events or rodeos, people spread out. Guests move between areas, sit, stand, and gather in different spots. A photo booth gives them a central point to return to. It keeps the event connected." },
    { type: "h3", text: "Solves Sharing Challenges in Rural Areas" },
    { type: "p", text: "Rural events don't always have perfect cell service. Digital gallery access ensures guests can still view and share photos easily after the event." },
    { type: "h3", text: "Works for All Ages" },
    { type: "p", text: "Sundre events often bring together families, kids, visitors, and long-time locals. Photo booths are one of the few things everyone can take part in." },
    { type: "h2", text: "Photo Booth Types Built for Sundre's Lifestyle" },
    { type: "p", text: "Each booth fits a different type of event." },
    { type: "h3", text: "Pole Photo Booth for Ranch Properties in Sundre" },
    { type: "p", text: "The pole booth is lightweight and portable. It works well for acreage weddings, backyard reunions, and family gatherings. It's easy to transport and set up on properties along Highway 22 or near the Red Deer River." },
    { type: "h3", text: "360 Photo Booth Sundre" },
    { type: "p", text: "The 360 booth adds movement and energy. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It's a strong fit for rodeo events, festivals, birthday parties, and large gatherings. It works especially well at events like the Sundre Pro Rodeo, where group interaction and energy are high." },
    { type: "h3", text: "Mirror Photo Booth Sundre" },
    { type: "p", text: "The mirror booth offers a more refined experience. Guests stand in front of the mirror and take photos naturally. It works well for weddings, indoor receptions, corporate events, and showers. It's simple and fits well into venues like the Sundre Community Centre." },
    { type: "h3", text: "Premium Backdrops & Audio Guest Books" },
    { type: "p", text: "Premium features add more depth to the experience. Backdrops can reflect pine forests, foothill landscapes, and ranch-style themes. Audio guest books capture voice messages, making them ideal for weddings, baby showers, and family events." },
    { type: "h2", text: "Prime Sundre Venues for Photo Booth Setups" },
    { type: "p", text: "Photo booths can be set up almost anywhere in Sundre. Here's how they fit into local venues." },
    { type: "h3", text: "Sundre Community Centre" },
    { type: "p", text: "Best for weddings, corporate events, and community gatherings. Capacity up to 400 guests, indoor space with power access, and flexible layout. This venue hosts over 150 events annually, making it one of the busiest event spaces in the area." },
    { type: "h3", text: "Sundre Ag Society Grounds" },
    { type: "p", text: "Best for rodeos, festivals, and outdoor events. Large outdoor space with indoor and outdoor flexibility and high traffic during peak events. This location hosts around 12 major outdoor events each year." },
    { type: "h3", text: "Legion Branch #300" },
    { type: "p", text: "Best for birthdays, baby showers, and smaller gatherings. Reliable indoor environment with consistent guest flow and an intimate event setting." },
    { type: "h3", text: "Rural Acreages Near the Red Deer River" },
    { type: "p", text: "Best for backyard weddings, family reunions, and private events. Open space placement with natural mountain and foothill views and flexible setup options." },
    { type: "h2", text: "Sundre Event Planning: Weather & Timing Essentials" },
    { type: "p", text: "Planning in Sundre requires awareness of timing and conditions." },
    { type: "h3", text: "Peak Summer Events" },
    { type: "p", text: "The busiest time for events includes the Sundre Pro Rodeo in late June, Stampede-style events in July, and summer tourism season. During rodeo weekend alone, demand for interactive services can increase by up to 300 percent." },
    { type: "h3", text: "Shoulder Season Planning" },
    { type: "p", text: "Spring and fall bring rain, cooler temperatures, and unpredictable weather. Indoor setups or backup options are often used during these months." },
    { type: "h3", text: "Outdoor Setup Windows" },
    { type: "p", text: "The best time for outdoor events is July to August. Around 75 percent of events during this period can comfortably stay outdoors." },
    { type: "h3", text: "Backdrop Selection" },
    { type: "p", text: "Local themes work best. Backdrops inspired by Dogpound Creek, Ya Ha Tinda Ranch, and foothill landscapes help photos feel connected to the location." },
    { type: "h2", text: "Why Sundre Locals Choose Photobooth Experience" },
    { type: "p", text: "Events in Sundre require flexibility and experience." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events need different setups. Having options makes it easier to choose what fits best." },
    { type: "h3", text: "Built for Mountain and Prairie Conditions" },
    { type: "p", text: "Weather, terrain, and layout all play a role. Setups are designed to handle those conditions." },
    { type: "h3", text: "Full Coverage Across Sundre" },
    { type: "p", text: "We service all areas, including community venues and rural acreages." },
    { type: "h3", text: "Easy Access to Photos and Videos" },
    { type: "p", text: "Guests can access their content after the event without extra steps." },
  ],
  faqs: [
    { q: "Sundre wedding photo booth rental — best options?", a: "Mirror booths are a strong choice for indoor receptions, offering interactive and polished photo experiences." },
    { q: "360 photo booth rental Sundre for rodeo weekend?", a: "Yes. 360 booths are ideal for capturing high-energy moments at events like the Sundre Pro Rodeo." },
    { q: "Photo booth for baby showers Sundre — what works?", a: "Audio guest books are a popular option for capturing personal messages at showers." },
    { q: "Backyard photo booth rental Sundre on acreages?", a: "Pole booths are portable and ideal for rural properties near the foothills." },
    { q: "Corporate photo booth Sundre for retreats?", a: "Premium setups with custom backdrops work well for lodge-style or corporate gatherings." },
    { q: "Mirror photo booth rental Sundre for birthdays?", a: "Yes. Mirror booths provide interactive experiences for both kids and adults." },
    { q: "Outdoor photo booth rental Sundre during summer showers?", a: "Yes. Portable booths can be adjusted for changing weather conditions." },
    { q: "Gender reveal photo booth Sundre — mountain themes?", a: "360 booths with themed backdrops create strong visual moments." },
    { q: "Family reunion photo booth rental Sundre options?", a: "Portable setups work well for large family gatherings on acreages." },
    { q: "What makes Sundre photo booth backdrops unique?", a: "Local foothill and ranch-inspired designs create a strong connection to the area." },
  ],
  image: "/locations/sundre.jpeg",
  ctaSubtext: "If you're planning an event in Sundre and want something that keeps people engaged, photo booth rentals are one of the easiest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
