"use client";
import LocationPage from "@/components/LocationPage";
import type { LocationData } from "@/components/LocationPage";

const data: LocationData = {
  city: "Carstairs",
  heroSubtitle: "Carstairs photo booth rentals for weddings, grad ceremonies, and events. Reliable setups, multiple booth options, and seamless service.",
  introParagraphs: [
    "Carstairs photo booth rentals bring something interactive to events that are built around community, family, and rural traditions.",
    "In Carstairs, events are local. People know each other, and gatherings feel personal whether they're held at the Rec Plex, a community hall, or a rural venue just outside town.",
    "That's where a photo booth fits in.",
    "It gives guests something to step into right away. No waiting, no pressure, just quick, natural moments captured throughout the event.",
  ],
  eventTypes: [
    "Weddings",
    "Baby showers",
    "Birthday parties",
    "Gender reveals",
    "Agricultural fairs",
    "Grad ceremonies",
    "Family reunions",
    "Community dinners",
  ],
  introClosure: "You can choose from pole booths, 360 booths, mirror booths, premium setups, audio guest books, and prairie-inspired backdrops. Everything is delivered and set up based on your event, with support so everything runs smoothly. Carstairs weather plays a big role in event planning. Chinook winds in the area can reach over 60 km/h, which means outdoor setups need to be properly anchored and stable.",
  contentBlocks: [
    { type: "h2", text: "Built for Carstairs Indoor and Outdoor Events" },
    { type: "p", text: "Events in Carstairs often move between indoor and outdoor spaces. Community halls, arenas, barns, and outdoor ceremony areas are all common. A photo booth needs to work in all of them." },
    { type: "h3", text: "Keeps Guests Engaged Throughout the Event" },
    { type: "p", text: "Every event has slower moments. Guests move between spaces, grab food, or take a break. A photo booth gives them something to come back to. It keeps the energy consistent without forcing interaction." },
    { type: "h3", text: "Handles Carstairs Weather Conditions" },
    { type: "p", text: "Carstairs events deal with chinook winds up to 60 km/h, sudden weather shifts, summer storms and hail, and early winter conditions. Photo booth setups need to be stable and adaptable to keep running in these conditions." },
    { type: "h3", text: "Fits Local Event Spaces" },
    { type: "p", text: "Most Carstairs events take place in community halls, recreation facilities, rural venues, and converted barns. Photo booths adapt easily to these environments without needing complex setups." },
    { type: "h2", text: "Your Carstairs Booth Collection" },
    { type: "p", text: "Each booth option works differently depending on your event." },
    { type: "h3", text: "Compact Pole Photo Booth in Carstairs" },
    { type: "p", text: "The pole booth is simple and space-efficient. It works well for smaller venues, community halls, grad ceremonies, and meetings and dinners. It fits easily into spaces like the Carstairs Rec Plex Multi-Purpose Room." },
    { type: "h3", text: "Carstairs 360 Photo Booth" },
    { type: "p", text: "The 360 booth adds movement and energy. Instead of still photos, it captures slow-motion video as the camera rotates around guests. It's a strong fit for weddings, community events, Stampede-style dances, and larger gatherings. It works well in open layouts like the TransCanada Room where guests can move freely." },
    { type: "h3", text: "Carstairs Mirror Photo Booth" },
    { type: "p", text: "The mirror booth offers a more refined experience. Guests stand in front of the mirror and take photos naturally. It fits well for weddings, showers, indoor receptions, and smaller venues. It pairs well with spaces like the Carstairs United Church Hall where layout is more intimate." },
    { type: "h3", text: "Carstairs Premium Photo Booth" },
    { type: "p", text: "The premium booth focuses on quality and flexibility. It allows larger group photos, consistent lighting, and high-quality images. It's ideal for weddings, community events, and larger receptions. It works well in venues like the Rec Plex arena lobby where larger crowds gather." },
    { type: "h3", text: "Carstairs Audio Guest Book" },
    { type: "p", text: "Photos show what happened. Audio captures what people said. The audio guest book allows guests to leave voice messages using a phone-style setup. It's a great addition for weddings, family gatherings, and community events. It creates something you can revisit long after the event." },
    { type: "h3", text: "Carstairs Premium Backdrops" },
    { type: "p", text: "Backdrops help define how your photos look. In Carstairs, they often reflect prairie landscapes, wheat fields, and rural settings. They help create a consistent look across all photos." },
    { type: "h2", text: "Perfect Carstairs Events for Photo Booth Rentals" },
    { type: "p", text: "Photo booths work across all types of events in Carstairs." },
    { type: "h3", text: "Carstairs Wedding Photo Booth" },
    { type: "p", text: "Weddings in Carstairs often take place at the Carstairs Rec Plex, TransCanada Room, or rural venues. A photo booth captures moments throughout the entire event, from ceremony to reception." },
    { type: "h3", text: "Community Events and Dinners" },
    { type: "p", text: "Spaces like the Carstairs United Church Hall host community dinners and gatherings. Photo booths add something interactive without changing the structure of the event." },
    { type: "h3", text: "Agricultural Fairs and Local Events" },
    { type: "p", text: "Carstairs has strong ties to agriculture. Events in the area often involve outdoor setups and large groups. Photo booths help keep guests engaged throughout the day." },
    { type: "h3", text: "Grad Ceremonies in Carstairs" },
    { type: "p", text: "Grad events often take place at local schools or community facilities. A photo booth gives students and families a way to capture moments easily." },
    { type: "h3", text: "Family Reunions and Gatherings" },
    { type: "p", text: "Community halls and rural venues are common for reunions. Photo booths provide a simple way to capture group photos." },
    { type: "h3", text: "Restaurant and Banquet Events" },
    { type: "p", text: "Some events take place in banquet rooms or restaurants with enough space. Photo booths can be set up in these environments as long as space allows." },
    { type: "h2", text: "Carstairs Venue-Specific Planning Guide" },
    { type: "p", text: "Planning in Carstairs requires attention to layout and logistics." },
    { type: "h3", text: "Carstairs Rec Plex" },
    { type: "p", text: "The Rec Plex includes a Multi-Purpose Room adjacent to the ice arena, arena lobby with high traffic during events, and power access along perimeter walls. Guest flow often moves from the arena lobby into event spaces, making placement important." },
    { type: "h3", text: "TransCanada Room" },
    { type: "p", text: "This venue offers full kitchen access, direct parking access, and an open layout for flexible setups. It works well for weddings and community dinners." },
    { type: "h3", text: "Carstairs United Church Hall" },
    { type: "p", text: "This space includes a historic interior, smaller capacity of 75 to 125 guests, and kitchen access. It's ideal for more intimate events." },
    { type: "h3", text: "Rural Banquet Halls" },
    { type: "p", text: "Many events take place in barns or rural venues outside of town. These locations often require stable base placement on gravel and additional setup considerations for outdoor areas. Chinook winds can reach 60 km/h, so proper anchoring is important for outdoor setups." },
    { type: "h2", text: "Why Carstairs Locals Choose Photobooth Experience" },
    { type: "p", text: "Events in Carstairs require flexibility. The service needs to match the environment." },
    { type: "h3", text: "Multiple Booth Options" },
    { type: "p", text: "Different events need different setups. Having multiple booth types allows you to choose what fits best." },
    { type: "h3", text: "Built for Rural and Community Events" },
    { type: "p", text: "Carstairs events are local and personal. Everything is designed to feel simple and natural for guests." },
    { type: "h3", text: "Full Coverage Across Carstairs" },
    { type: "p", text: "We service the entire area, including surrounding rural locations." },
    { type: "h3", text: "Easy Access to Photos and Videos" },
    { type: "p", text: "Guests can access their content after the event without extra steps." },
  ],
  faqs: [
    { q: "Is a 360 photo booth a good fit for Carstairs Rec Plex events?", a: "Yes. It captures movement and group interaction, making it ideal for larger event spaces." },
    { q: "How does a mirror photo booth work at Carstairs events?", a: "Guests stand in front of the mirror and take photos naturally. It works well in both large and small venues." },
    { q: "Can photo booths handle Carstairs wind conditions?", a: "Yes. Setups are designed with stability in mind to handle strong chinook winds." },
    { q: "Why add an audio guest book to a Carstairs event?", a: "It captures voice messages from guests, creating something more personal than photos." },
    { q: "Can backdrops match Carstairs rural themes?", a: "Yes. Backdrops can reflect prairie and agricultural styles." },
  ],
  image: "/locations/Carstairs.jpg",
  ctaSubtext: "If you're planning an event in Carstairs and want something that keeps people engaged, photo booth rentals are one of the easiest ways to make it happen. Photobooth Experience handles delivery, setup, and support so everything runs smoothly. Reach out today to check availability and get a quote for your event.",
};

export default function Page() {
  return <LocationPage data={data} />;
}
